### PR TITLE
Print ctr ID if neither STDOUT and STDERR are attached

### LINKED ISSUE #604: podman run -a stdin: does not detach stdout
Running with `-a stdin` produces output on stdout 
```
# podman run -a stdin fedora date
Tue Apr 10 17:51:57 UTC 2018
# podman run -a stdin fedora ls /nonesuch
ls: cannot access '/nonesuch': No such file or directory
```
docker emits a container ID in both cases:
```
# docker run -a stdin fedora date
56f3a8de1746667b401181c09f844332da972861de81b47711583e3f6393c230
# docker run -a stdin fedora ls /nonesuch
7ad6159f3dbc3117eb66e0a4ce2caa2e13b00a483e2de4694dbcea9933d6c42a
```
(output accessible as expected via `docker logs`)

podman-0.4.1-1.gitb51d327.fc27

### PR DESCRIPTION
**Pull request by mheon**
Fixes #604 (again)

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
@mheon sign your PR

**Comment by mheon** [comment]
@rhatdan It has a signoff. I managed to mess up one of the tests I added, though. Fixing now.

**Comment by mheon** [comment]
Tests are green. Going to merge.
@rh-atomic-bot r=rhatdan

**Pull request closed without merging**
