### PR TITLE
Test to verify overlay quotas work, show container overhead on quota

### PR DESCRIPTION
**Pull request by haircommander**
Signed-off-by: haircommander <pehunt@redhat.com>

### CODE REVIEW

**Comment by haircommander** [comment]
@rhatdan PTAL

**Comment by rhatdan** [comment]
NICE 
LGTM
@nalind @rhvgoyal @giuseppe PTAL

**Comment by TomSweeneyRedHat** [comment]
@haircommander looks like some test unhappiness here

**Comment by haircommander** [comment]
uh turns out aws boxes don't have loop devices... Should I create them if this is the case?

**Comment by rhatdan** [comment]
@haircommander Yes

**Comment by haircommander** [comment]
@rhatdan if this doesn't work i don't think It can be included in CI, it's the only solution the internet had to offer :\

**Comment by haircommander** [comment]
I will keep wrestling with it tomorrow, but it seems the amazon instances aren't playing nice, so this may not work in CI :'(

**Comment by mheon** [comment]
@haircommander If you can't get it working on CI, we should see about adding it to the baseline test script maintained by @TomSweeneyRedHat

**Comment by TomSweeneyRedHat** [comment]
@haircommander if you decide to move it there, the baseline tests are at: https://github.com/projectatomic/libpod/blob/master/test/test_podman_baseline.sh

**Comment by haircommander** [comment]
@TomSweeneyRedHat @rhatdan @mheon anyone know why this keeps failing? I've repushed like 4 times and I keep getting the same error

**Comment by mheon** [comment]
Cloud podman tests seem to be failing everywhere right now - I'd ignore them at the moment

**Comment by rhatdan** [comment]
Right this failure is a problem with the cloud image. Caused by a bad libsemanage package.

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
