### PR TITLE
Refactor unittest for varlink component

### PR DESCRIPTION
**Pull request by jwhonce**
- Allow unittest's to run as normal user
- Refactor tests to use unittest features
- Refactor tests to use fixtures to track resources
- Update test runner script to clean up on failure

Signed-off-by: Jhon Honce <jhonce@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
@baude We're already running the varlink tests in the integration test suite, right?

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
@jwhonce Second PR is not signed.  Merge together or sign second one.

**Comment by jwhonce** [comment]
@rhatdan All signed now.

**Comment by rhatdan** [comment]
@baude @mheon @umohnani8 PTAL

**Comment by baude** [comment]
LGTM.  I assume next steps is to populate the image tests?

**Comment by umohnani8** [comment]
LGTM

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
