### PR TITLE
Fix panic when no image is given

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
LGTM

**Comment by mheon** [comment]
@rh-atomic-bot +r

**Comment by cgwalters** [comment]
@mheon It's `r+`, not `+r` 😄

**Comment by mheon** [comment]
@cgwalters "oops"

**Comment by mheon** [comment]
@rh-atomic-bot r+

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by rhatdan** [comment]
@rh-atomic-bot r=mheon

**Comment by cgwalters** [comment]
Hmm actually do we have homu set up for this repo?  Let me check...

**Comment by rhatdan** [comment]
It has worked in the past.

**Comment by cgwalters** [comment]
Yeah, ops (me) snafu.  See also https://lists.centos.org/pipermail/ci-users/2017-November/000743.html

**Comment by cgwalters** [comment]
Try again?

**Comment by rhatdan** [comment]
@rh-atomic-bot r=mheon

**Pull request closed without merging**
