### PR TITLE
Re-add FFJSON for container and pod structs

### PR DESCRIPTION
**Pull request by mheon**
The struct that was giving us trouble was removed when we reworked how we handled storing the network information CNI handed us back. This seemingly fixed things.

### CODE REVIEW

**Comment by rhatdan** [comment]
We need something into the Makefile to autogenerate these.

```
containers_ffjson.go: containers.go
	$(RM) $@
	ffjson containers.go
```

**Comment by TomSweeneyRedHat** [comment]
LGTM, would like to see the Makefile change.

**Comment by mheon** [comment]
Added FFJSON generation to makefile

**Comment by mheon** [comment]
Huh. @baude your RPM regression test actually works.

**Comment by lsm5** [comment]
@mheon @baude what's the rpm issue here? is it just that we need to update spec to use ffjson_generate target?

**Comment by mheon** [comment]
@lsm5 It seems to be trying to ffjson_generate during RPM build, where we don't have a working ffjson binary or an easy way to get one without `go get`

**Comment by mheon** [comment]
Actually, that could be me being careless with makefile dependencies - let me see...

**Comment by mheon** [comment]
Alright, all set now

**Comment by rhatdan** [comment]
LGTM
@rh-atomic-bot r+

**Pull request closed without merging**
