### PR TITLE
Use debugf to allow parsing of format specifier

### PR DESCRIPTION
**Pull request by surajssd**
Signed-off-by: Suraj Deshmukh <surajd.service@gmail.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
@surajssd Needs a rebase.

**Comment by rhatdan** [comment]
@surajssd needs rebase.

**Comment by surajssd** [comment]
@TomSweeneyRedHat done!

**Comment by rhatdan** [comment]
bot, retest please

**Comment by mheon** [comment]
@surajssd Can you do a quick rebase+repush? We were having CI issues last week that should be resolved.

**Comment by rhatdan** [comment]
@surajssd Rebase please

**Comment by surajssd** [comment]
I did push the upgraded one, but master seems to be broken:

```console
$ gcm                                         
Switched to branch 'master' 
$ gpum                                        
From github.com:projectatomic/libpod                
 * branch              master     -> FETCH_HEAD     
Already up-to-date.   
$ git status                                  
On branch master
nothing to commit, working tree clean
$ make                                        
make -C conmon                                      
make[1]: Entering directory '/home/hummer/go/src/github.com/projectatomic/libpod/conmon'                 
mkdir -p ../bin/                                    
cc -o ../bin/conmon conmon.o cmsg.o -std=c99 -Os -Wall -Wextra -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -lglib-2.0                                                                                   
make[1]: Leaving directory '/home/hummer/go/src/github.com/projectatomic/libpod/conmon'                  
go build -ldflags '-s -w -X main.gitCommit="12682aa475db17d99eb0cfc5efad20e1b9f3685f" -X main.buildInfo=1513014694 -X main.kpodVersion=0.1' -tags "seccomp     selinux" -o bin/kpod github.com/projectatomic/libpod/cmd/kpod                                           
# github.com/projectatomic/libpod/libpod            
libpod/sql_state.go:108:3: s.lock undefined (type *SQLState has no field or method lock)                 
libpod/sql_state.go:109:9: s.lock undefined (type *SQLState has no field or method lock)                 
make: *** [Makefile:88: kpod] Error 2
```

**Comment by mheon** [comment]
@surajssd Oops - we did a bunch of manual merges this morning since CI is still iffy. #117 should resolve this.

**Comment by TomSweeneyRedHat** [comment]
Happy green test buttons, let's merge this!

**Comment by mheon** [comment]
LGTM
@rhatdan PTAL

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by rhatdan** [comment]
Looks like Homu is still not responding.   Manually merging.

**Pull request merged**
