### PR TITLE
Makefile: Fix typo podmon -> podman

### PR DESCRIPTION
**Pull request by marcosps**
This typo was introduced in 3aa63b2b

Signed-off-by: Marcos Paulo de Souza <marcos.souza.org@gmail.com>

### CODE REVIEW

**Comment by mheon** [comment]
Nice catch, LGTM

**Comment by TomSweeneyRedHat** [comment]
bot, add author to whitelist

**Comment by TomSweeneyRedHat** [comment]
LGTM, @marcosps TYVM for the contribution!

**Comment by marcosps** [comment]
@TomSweeneyRedHat I'm happy to contribute to the containers environment!

**Comment by rhatdan** [comment]
bot, retest this please

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
