### PR TITLE
Remove tutorial link from README.md and move Install Instructions

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>

I've removed the tutorial link as it was pointing to CRI-O's link.   @ipbabble  will be working on a tutorial and will add a link when it's complete, hopefully early next year.

Recently Buildah moved the install instructions into a separate page, I've done so for libpod.  I also moved the CNI Network there too as that felt more setup related.  @anarcat I think this addresses #114

### CODE REVIEW

**Comment by rhatdan** [comment]
@TomSweeneyRedHat When @mheon merges his patches for networking. we will need that CNI description.
Otherwise LGTM

**Comment by TomSweeneyRedHat** [comment]
@rhatdan I've put the CNI Network info on the install.md page.  It felt like it fits better there.  If you think it belong on the README.md still I'll move it back.

**Comment by anarcat** [comment]
well, it "resolves" #114 in that it removes the broken link, but doesn't resolve the issue that there's no tutorial. :p

**Comment by rhatdan** [comment]
@TomSweeneyRedHat My mistake, I read the "I moved the CNI ..." as "I removed the CNI..."

**Comment by rhatdan** [comment]
@TomSweeneyRedHat You are being bitten by Whitespace.

**Comment by TomSweeneyRedHat** [comment]
Ugh!  A blank line at the end of the install.md caused the failure.

**Comment by ipbabble** [comment]
Anti-fragility ;-)

William Henry
Senior Consulting Software Engineer
Red Hat
Colorado, USA.

**Comment by rhatdan** [comment]
LGTM
@rh-atomic-bot r+

**Pull request closed without merging**
