### PR TITLE
update gitvalidation epoch

### PR DESCRIPTION
**Pull request by baude**
updating the gitvalidation epoch to speed up
git validations.

Signed-off-by: baude <bbaude@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests.

**Comment by rhatdan** [comment]
Will merge once tests pass.

**Comment by rhatdan** [comment]
Merging since bot seems to be offline.

**Pull request merged**
