### PR TITLE
ci/papr: Disable and remove docker on FAH27

### PR DESCRIPTION
**Pull request by cgwalters**
For now, per discussion e.g. `iptables` rules can interfere.

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
Looks like something is trying to connect to docker after you tried to kill it in the tests.

**Comment by cgwalters** [comment]
> Looks like something is trying to connect to docker after you tried to kill it in the tests.

OK, I took a stab at reworking this :arrow_up:  - let's see.

**Comment by baude** [comment]
@cgwalters I can make this work for us but I am already doing something similar with the cloud image.  That's why I was asking about having a customized predeployed image for FA27 that ran podman and not docker.

**Comment by cgwalters** [comment]
Looks like this was obsoleted by https://github.com/projectatomic/libpod/pull/524

**Pull request closed without merging**
