### PR TITLE
Update gitvalidation epoch

### PR DESCRIPTION
**Pull request by mheon**
Homu merged a commit without a signoff, update our Gitvalidation epoch to after said commit to prevent problems.

### CODE REVIEW

**Comment by mheon** [comment]
This should unblock the test suite

**Comment by rhatdan** [comment]
LGTM

**Comment by vrothberg** [comment]
LGTM :+1:

**Comment by mheon** [comment]
I'm going to wait to make sure Travis passes before merging.

**Comment by mheon** [comment]
Alright, assuming the others are just flakes...
@rh-atomic-bot r=vrothberg

**Comment by mheon** [comment]
That error makes no sense, so I'm going to retry hoping it's a flake
@rh-atomic-bot retry

**Comment by baude** [comment]
bot, retest this please

**Comment by mheon** [comment]
It seems like it doesn't like the first and last commit being validated being the same. We might need to force merge something else with a good signoff first and then set that commit's ID as the epoch.

**Comment by giuseppe** [comment]
@rh-atomic-bot retry

**Pull request closed without merging**
