### PR TITLE
Ginkgo Tests: ps, pull, push and rm

### PR DESCRIPTION
**Pull request by baude**
Migrate ps, pull, push, and rm from bats to ginkgo.

Also, fixed a conditional issue with adding ports
when an image defines the port and the user wants
to override it.

Signed-off-by: baude <bbaude@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
bot, retest this please

**Comment by baude** [comment]
bot, retest this please

**Comment by baude** [comment]
bot, retest this please

**Comment by mheon** [comment]
LGTM

**Comment by baude** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
