### PR TITLE
Update containers/image

### PR DESCRIPTION
**Pull request by mheon**
New pinned commit is 1ac68f9365b51b802da6931c6751e6081af7e0bd

### CODE REVIEW

**Comment by mheon** [comment]
Probably going to hold off until https://github.com/containers/image/pull/428 merged. Leaving open but tagging WIP

**Comment by rhatdan** [comment]
@mheon We had a few other commits including this one, could you vendor in latest and we can merge.

**Comment by mheon** [comment]
Updated to pin commit b327f751c16e4a189fdcde4ea36be67cc964c605

Removing WIP label

**Comment by baude** [comment]
LGTM, lets do this.

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
