### PR TITLE
Fix typo in label field option

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@mheon @umohnani8 @baude @TomSweeneyRedHat PTAL

**Comment by mheon** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
Change LGTM, but looks like you hit a hiccup with the CentOs test.  Wasn't able to get a good checksum from the repo?

**Comment by mheon** [comment]
bot, retest this please

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
