### PR TITLE
Log podman build failures in papr

### PR DESCRIPTION
**Pull request by mheon**
Per @jlebon in #872

### CODE REVIEW

**Comment by baude** [comment]
LGTM

**Comment by mheon** [comment]
We finally have debug logs for FAH27!

**Comment by mheon** [comment]
@nalind @TomSweeneyRedHat  We're getting a `time="2018-06-01T15:54:18Z" level=error msg="error reading from pipe 9: resource temporarily unavailable"` out of `podman build` - any idea what's going on?

**Comment by jlebon** [comment]
That's odd. When I just redirect stderr to a file, I do get a backtrace in the file. Though that doesn't seem to be the case here. Anyway, you can see the actual backtrace I posted in #872.

Looking at #873, it looks like FAH28 isn't hitting this. Probably still worth investigating the failure, though.

**Comment by mheon** [comment]
bot, retest this please

**Comment by mheon** [comment]
Going to see if the failure is consistent or if we get different errors

**Comment by TomSweeneyRedHat** [comment]
The error you're seeing is happening when we're creating the container and are trying to capture the output from:

```
errorFds = []int{stdioPipe[unix.Stdout][0], stdioPipe[unix.Stderr][0]}
```
The code all looks to be OK, and not something that should fail.  The line it's failing on is:

```
nread, err := unix.Read(fd, buf)
```

and we've two instances so I'm not completely sure which of the two blew up..  I'm not sure about the why....

**Comment by rhatdan** [comment]
Rebase please.

**Comment by mheon** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
