### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by mavit**

### CODE REVIEW

**Comment by mheon** [comment]
Good catch, LGTM

**Comment by mheon** [comment]
bot, add author to whitelist

**Comment by TomSweeneyRedHat** [comment]
LGTM and thanks @mavit !

**Comment by mheon** [comment]
@mavit Can you add a Signed-off-by to your commit? `git commit --amend -s` and then a `git push --force ...` should be enough

**Comment by rhatdan** [comment]
Thanks @mavit 
@rh-atomic-bot r+

**Pull request closed without merging**
