### PR TITLE
Clear up fragments of the old api

### PR DESCRIPTION
**Pull request by umohnani8**
As everything is being moved over to the new container api
removing files that depended on the old api
   
Signed-off-by: umohnani8 <umohnani@redhat.com>

### CODE REVIEW

**Comment by umohnani8** [comment]
Waiting on https://github.com/projectatomic/libpod/pull/106 and https://github.com/projectatomic/libpod/pull/113

**Comment by TomSweeneyRedHat** [comment]
@umohnani8 looks like you need to rebase.

**Comment by rhatdan** [comment]
@umohnani8 Needs a rebase.

**Comment by umohnani8** [comment]
Ready to merge once tests are green

**Comment by mheon** [comment]
LGTM
@rhatdan PTAL

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
