### PR TITLE
Update the vendoring of github.com/opencontainers/selinux

### PR DESCRIPTION
**Pull request by rhatdan**
THis should make libpod easier to build on non linux platforms.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@vbatts @baude @mheon @umohnani8 @TomSweeneyRedHat PTAL

**Comment by mheon** [comment]
LGTM once tests green

**Comment by baude** [comment]
bot, retest this please

**Comment by umohnani8** [comment]
LGTM

**Comment by mheon** [comment]
Congrats on PR #1000 @rhatdan 
@rh-atomic-bot r+

**Comment by TomSweeneyRedHat** [comment]
Me thinks @rhatdan was hiding in the weeds waiting to grab PR #1000.  Nice milestone all for Podman!

Oh yeah, belated LGTM.

**Comment by rhatdan** [comment]
@mheon Do I get a reward?

**Comment by mheon** [comment]
@rhatdan There were cookies, but I ate them all :cry:

**Comment by vbatts** [comment]
🍪🍪🍪🍪🍪🍪

**Pull request closed without merging**
