### PR TITLE
Remove old varlink tests

### PR DESCRIPTION
**Pull request by jwhonce**
* Replaced by tests in libpod/contrib/python/test

Signed-off-by: Jhon Honce <jhonce@redhat.com>

### CODE REVIEW

**Comment by jwhonce** [comment]
@mheon I suspect after is safer, only overlap is in the Makefile

**Comment by rhatdan** [comment]
@jwhonce Needs rebase.

**Comment by jwhonce** [comment]
@rh-atomic-bot retry

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
