### PR TITLE
sort containers and images by create time

### PR DESCRIPTION
**Pull request by baude**
When running podman ps or podman images, the containers and images should
be sorted by newest to oldest.

Resolves: #830

Signed-off-by: baude <bbaude@redhat.com>

### CODE REVIEW

**Comment by baude** [comment]
@rhatdan ptal

**Comment by baude** [comment]
bot, retest this please

**Comment by TomSweeneyRedHat** [comment]
o You probably want to update the examples on the manpage.
o It would be good to have a note somewhere in the man page listing the sort order used.
o Wish list, it would be nice to allow the user to sort that list by at least container-name via some --sort param.

The code as is LGTM

**Comment by rhatdan** [comment]
Lets get it by date first, and then --sort param later.

**Comment by rhatdan** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
Sure thing on the sort param.  Not at all necessary for this PR, just wanted to throw it out there for future consideration.

**Comment by mheon** [comment]
LGTM
@rh-atomic-bot r+

**Comment by TomSweeneyRedHat** [comment]
FYI, the podman ps man page really should be touched up....

**Comment by mheon** [comment]
@TomSweeneyRedHat I think our examples for `ps` are fine, since the original behavior was sorting like this - we regressed after swapping to boltdb.

Podman images probably does need a touchup though.

**Pull request closed without merging**
