### PR TITLE
Add additional storage with test image

### PR DESCRIPTION
**Pull request by rhatdan**
This patch adds an overlay storage with a testimg based on alpine
already installed.  I also modified kpod_history.bats to no longer
pull images, but to use the test image.  This should speed up the
testing process, since we don't have to constantly pull images.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@baude @nalind PTAL

**Comment by nalind** [comment]
This breaks if we ever change how we store things in overlay, and assumes we're using overlay, which isn't always the case during testing.  Can we grab the copyimg test helper from cri-o, and use it to save a freshly-pulled copy of the image to a secondary location, restoring it from there instead of pulling it if we see that location populated?

**Comment by rhatdan** [comment]
Sure we can look to do this, but I guess I would like to be able to test to make sure the additonalstores stuff works also.  Perhaps we should just add tests cases for it, and only run them if overlay back end is used.

**Comment by baude** [comment]
@rhatdan I think we can close this one ?

**Comment by rhatdan** [comment]
I actually want to add a tests for this, but we need to close it for its orignal purpose, yes.

**Pull request closed without merging**
