### PR TITLE
Add support for mimicing docker CLI

### PR DESCRIPTION
**Pull request by rhatdan**
Simple scripts to allow easier transition from Docker package to podman.

### CODE REVIEW

**Comment by mheon** [comment]
LGTM

**Comment by cgwalters** [comment]
I think this would be better if there was a one-liner bash alias one could use; as is an RPM form of this would `Conflict: docker` right?

So install as `/usr/bin/podman-docker` or something then it's just:
`echo 'alias docker podman-docker' >> ~/.bashrc`?

**Comment by rhatdan** [comment]
@cgwalters Legal says you have to indicate that the user is not executing Docker when executing the docker command, which is why I did it as a script.  I am not trying to fool anyone that podman is the same as docker.

**Comment by rhatdan** [comment]
But yes if we ever decided to ship a podman-docker package then it would need to conflict with the docker package.

**Comment by TomSweeneyRedHat** [comment]
I'm not feeling this.  I've never been a fan of overwriting files from an rpm that the current rpm didn't install itself.  I'd say keep them separate and let someone run docker and podman on the same machine if they want to.  I don't think they would, but who knows.

The code looks fine for what you're trying to do though, I'll leave it up to you about moving forward or not.

**Comment by rhatdan** [comment]
If we were to ship it, we would as a separate package that would not be installable if docker was installed.

**Comment by rhatdan** [comment]
@umohnani8 @baude PTAL

**Comment by baude** [comment]
looks ok

**Comment by rhatdan** [comment]
Homu seems to be broken.  Merging manually

**Comment by cgwalters** [comment]
> Homu seems to be broken. Merging manually

FWIW that looks like an rpm-md (yum) repo flake, not homu itself.

**Pull request merged**
