### PR TITLE
Add 'podman restart' asciinema

### PR DESCRIPTION
**Pull request by mheon**

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM, but it woulda been nice to attach to the restarted container and cat test.txt one more time.

Did you sign this commit?  I'm not seeing it in the description.

**Comment by mheon** [comment]
Commit should be signed, yeah. Good call about the attach/cat, but it took the better part of an hour to do it without major typos, so I'll save that bit for later

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
