### PR TITLE
Vendor in latest github.com/projectatomic/buildah

### PR DESCRIPTION
**Pull request by rhatdan**
This adds support for Dockerfile.in and fixes some limits
issues on docker build

Also adds support for podman build to read Dockerfile from stdin.

cat Dockerfile | podman build -f - .

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@vrothberg @mheon @baude @TomSweeneyRedHat @umohnani8 PTAL

**Comment by mheon** [comment]
Damn it, Homu let in another commit with a bad signoff

**Comment by mheon** [comment]
Hold merging this for a second so I can get the gitvalidation epoch updated

**Comment by mheon** [comment]
#1210 should fix the tests

**Comment by mheon** [comment]
LGTM
@rh-atomic-bot r+

**Pull request closed without merging**
