### PR TITLE
Vendor in latest container/storage for devicemapper support

### PR DESCRIPTION
**Pull request by rhatdan**
container/storage now supports devicemapper options that allow you to
configure it.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
Changes LGTM, but tests aren't hip.

**Comment by rhatdan** [comment]
Now passing tests.

@baude @TomSweeneyRedHat @umohnani8 @wking @mheon PTAL

**Comment by mheon** [comment]
LGTM

**Comment by rhatdan** [comment]
@rh-atomic-bot r=mheon

**Pull request closed without merging**
