### PR TITLE
Use podman to test podman on FAH

### PR DESCRIPTION
**Pull request by baude**
Signed-off-by: baude <bbaude@redhat.com>

### CODE REVIEW

**Comment by baude** [comment]
bot, retest this please

**Comment by TomSweeneyRedHat** [comment]
LGTM, assuming happy tests.

**Comment by rhatdan** [comment]
LGTM
@rh-atomic-bot r+

**Comment by rhatdan** [comment]
Oops can't approve until @baude takes off WIP flag.

**Comment by baude** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
