### PR TITLE
Change sudo examples to use $ instead of $

### PR DESCRIPTION
**Pull request by rhatdan**
sudo is not required when running as root, and # indicates
that you are already root.  $ indicates you are not root.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Fixes https://github.com/projectatomic/libpod/issues/207

**Comment by rhatdan** [comment]
@ipbabble PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM, but probably want to let @baude weigh in.

**Comment by baude** [comment]
whatever makes people happy

**Comment by rhatdan** [comment]
I am not going to fight with this. Error is unrelated, this is a docs only change. Will merge manually.

**Comment by ipbabble** [comment]
The change LGTM. I had a gist from the Docker man page/tutorial days that I wanted to make into a podman tutorial. I will take a look and see where it fits in.  But most of it would be around -v  options.

https://gist.github.com/ipbabble/c7f231d6ebf596e61cd6

**Pull request merged**
