### PR TITLE
Remove all images

### PR DESCRIPTION
**Pull request by baude**
Add -a/--all to rmi so a user can remove
all images quickly.

Signed-off-by: baude <bbaude@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
Should we allow arguments to be passed when --all is present? I think specifying image specific images is pointless when we already have the "all images must go" flag set.

**Comment by mheon** [comment]
Nevermind, already handled. I shouldn't be doing this on my day off.

LGTM

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
Failing tests.

**Comment by mheon** [comment]
Tests green, merging
@rh-atomic-bot r+

**Pull request closed without merging**
