### PR TITLE
[RFC] Add support for multiple networks

### PR DESCRIPTION
**Pull request by dcbw**
podman run --network=net1,net2,foobar ...

@baude @mheon @rhatdan

### CODE REVIEW

**Comment by rhatdan** [comment]
I would prefer we change the CLI to use a StringSlice for --net, then you could specify

--net net1 --net net2 --net fedora ...

**Comment by dcbw** [comment]
One thing I think we have to do is cache which networks were given to 'run' or 'create' so that we can intelligently tear them down later.  Otherwise you'd have to make sure you passed the same set of -net options to kill which could be error-prone.

**Comment by baude** [comment]
@dcbw you have a git validation error in there ... if you can fix that, tests will run ... ping us for help on the validation error if this is new to  you.

**Comment by rhatdan** [comment]
@dcbw This needs a rebase.

**Comment by dcbw** [comment]
@rhatdan yeah, I will.  I also tried to use StringSlice but that's going to be complicated because NetMode is tied in with the docker HostConfig and inspect stuff.

**Comment by baude** [comment]
closing in favor of #1082 ... thanks for your contribution @dcbw

**Pull request closed without merging**
