### PR TITLE
Pass newly-added --log-level flag to Conmon

### PR DESCRIPTION
**Pull request by mheon**
This may require a new Conmon commit in the tests - will know once they run

### CODE REVIEW

**Comment by baude** [comment]
LGTM, nice

**Comment by vrothberg** [comment]
Can we add the version requirement on conmon to the release notes? Currently, the openSUSE packages go the lazy path just require CRI-O to be installed. I was hoping for a dedicated conmon project to ease packaging, but I think it's time to have a dedicated podman-conmon package in openSUSE.

**Comment by mheon** [comment]
The CI failures are a bad `conmon` commit - need to update the one we're using.

**Comment by mheon** [comment]
@vrothberg I think breaking `conmon` out is good decision - it doesn't really make much sense to keep in CRI-O anymore.

I actually didn't notice this conmon change until it landed, so when we bumped the package in Fedora with the new Podman release, we weren't passing the flag, which caused segfaults in conmon. We really need Podman tests on new Conmon commits.

**Comment by rhatdan** [comment]
@mrunalp WDYT about breaking conmon out of CRI-O into its own package, Say github.com/containers/conmon

**Comment by mheon** [comment]
Alright, conmon commit seems to have fixed things.

I agree with @vrothberg that we should advise on the current required conmon commit somewhere, but I'm not sure where is best. We could use the README, but the instructions for building Conmon are in the tutorial.

**Pull request closed without merging**
