### PR TITLE
Vendor in lots of kubernetes stuff to shrink image size

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
+300,000 -700,000... One of the biggest single-patch diffs I've ever seen. LGTM pending tests.

**Comment by mheon** [comment]
Looks like build errors - might need a higher version of golang.org/x/crypto?

**Comment by rhatdan** [comment]
bot, retest this please

**Comment by mheon** [comment]
Travis failure looks like a flake. LGTM

**Comment by baude** [comment]
i kicked travis, it passed

**Comment by mheon** [comment]
Alright, tests are green, going to merge
@rh-atomic-bot r+

**Comment by mheon** [comment]
sig-proxy failed, probably a flake
@rh-atomic-bot retry

**Comment by mheon** [comment]
@rh-atomic-bot retry

**Pull request closed without merging**
