### PR TITLE
Turn off IRC reporting until we have our own channel

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@runcom PTAL

**Comment by runcom** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM, I'd rather leave it on until the name/irc channel dust settles though.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat @runcom asked us to stop dirtying CRI-O IRC.

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
