### PR TITLE
WIP: Double timeout for papr in attempt to stop test errors

### PR DESCRIPTION
**Pull request by mheon**
Don't merge until we verify this resolves the issue

### CODE REVIEW

**Comment by mheon** [comment]
bot, retest this please

**Comment by TomSweeneyRedHat** [comment]
LGTM
Fingers crossed.

**Comment by mheon** [comment]
bot, retest this please

**Comment by rhatdan** [comment]
bot, retest this please

**Comment by mheon** [comment]
Well, the increased timeout was unable to stop f28 cloud podman from timing out...

**Comment by mheon** [comment]
The listed timeout appears to have gotten shorter, not longer

**Comment by mheon** [comment]
bot, retest this please

**Comment by mheon** [comment]
The timeouts do not actually seem to have changed.

**Comment by mheon** [comment]
Fix merged elsewhere

**Pull request closed without merging**
