### PR TITLE
Fix output of kpod images

### PR DESCRIPTION
**Pull request by umohnani8**
Update the output of kpod images to match that of docker images

Signed-off-by: umohnani8 <umohnani@redhat.com>

### CODE REVIEW

**Comment by umohnani8** [comment]
The only difference now is that the space between the columns is a tab after the longest value in the column, since I am using Go's tabwriter package to allow for the column widths to be dynamic based on the length of the longest value.
So column widths are longest value in column + tab.

**Comment by mheon** [comment]
LGTM

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by TomSweeneyRedHat** [comment]
IDK if it would work well or not, but it might be nice to have some sample output in the man page.  Do we need to update a video tutorial?

**Comment by rhatdan** [comment]
Sure anything to improve the man pages is always good.

**Pull request merged**
