### PR TITLE
Makefile: Use 'git diff' to show gofmt changes

### PR DESCRIPTION
**Pull request by wking**
This makes fixing errors easier.  Before this commit, errors looked [like][1]:

    libpod/container_linux.go:1::warning: file is not gofmted with -s (gofmt)

But that's not very helpful when your local `gofmt` thinks the file is fine.  With this commit, errors will look like:

```console
$ make gofmt
find . -name '*.go' ! -path './vendor/*' -exec gofmt -s -w {} \+
git diff --exit-code
diff --git a/libpod/container_internal.go b/libpod/container_internal.go
index df4de3fe..22b39870 100644
--- a/libpod/container_internal.go
+++ b/libpod/container_internal.go
@@ -1,7 +1,7 @@
 package libpod

 import (
-"bytes"
+       "bytes"
        "context"
        "encoding/json"
        "fmt"
make: *** [Makefile:87: gofmt] Error 1
```

(or whatever, I just stuffed in a formatting error for demonstration purposes).

Also remove the helper script in favor of direct Makefile calls, because with Git handling difference reporting and exit status, this becomes a simpler check.  find's -exec, !, and -path arguments [are specified in POSIX][2].

This pull-request ports kubernetes-incubator/cri-o#1281 to libpod.

[1]: https://travis-ci.org/projectatomic/libpod/jobs/398460911#L865
[2]: http://pubs.opengroup.org/onlinepubs/9699919799/utilities/find.html

### CODE REVIEW

**Comment by mheon** [comment]
LGTM

**Comment by mheon** [comment]
bot, retest this please

**Comment by mheon** [comment]
bot, retest this please

**Comment by mheon** [comment]
Travis failure is #1040 

@rhatdan @TomSweeneyRedHat @baude PTAL

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
