### PR TITLE
Added ps --pod option

### PR DESCRIPTION
**Pull request by haircommander**
Signed-off-by: haircommander <pehunt@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
LGTM. Only comment: Should we display nothing for containers with no pod, or maybe <none> similar to images with no tags?

**Comment by haircommander** [comment]
@mheon I think blank is conforms most with the rest of ps: ports for example is just blank.

**Comment by mheon** [comment]
Alright, SGTM

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
