### PR TITLE
Update podman_tutorial.md

### PR DESCRIPTION
**Pull request by warmchang**
Fix the familiarizing-yourself-with-podman link.

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by warmchang** [comment]
@mheon 
The previous commition was directly operated in github page, and I added the sign & re-push.
Please check it, thanks!

**Comment by mheon** [comment]
@warmchang Signoff looks good, thanks

**Comment by mheon** [comment]
bot, add author to whitelist

**Comment by mheon** [comment]
LGTM, good for merge once tests are green

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
