### PR TITLE
Fix bash command

### PR DESCRIPTION
**Pull request by rhatdan**

### CODE REVIEW

**Comment by rhatdan** [comment]
Script/command completions are broken without this fix.

**Comment by TomSweeneyRedHat** [comment]
LGTM, but you need to sign it @rhatdan

**Comment by rhatdan** [comment]
oops.

**Comment by rhatdan** [comment]
@baude PTAL

**Comment by rhatdan** [comment]
@umohnani8 PTAL

**Comment by umohnani8** [comment]
LGTM

**Comment by rhatdan** [comment]
@rh-atomic-bot r=umohnani8

**Pull request closed without merging**
