### PR TITLE
Start using github.com/seccomp/containers-golang

### PR DESCRIPTION
**Pull request by rhatdan**
User newer seccomp bindings from the seccomp upstream

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
LGTM

**Comment by mheon** [comment]
@rhatdan Looks like seccomp/containers-golang is missing a types subpackage?

**Comment by rhatdan** [comment]
bot, retest this please

**Comment by rhatdan** [comment]
@baude @giuseppe @umohnani8 @TomSweeneyRedHat PTAL

**Comment by giuseppe** [comment]
LGTM

**Comment by rhatdan** [comment]
@rh-atomic-bot r=giuseppe

**Pull request closed without merging**
