### PR TITLE
We are using err in defer function, needs to be defined name

### PR DESCRIPTION
**Pull request by rhatdan**
Since we are checking if err is non nil in defer function we need
to define it, so that the check will work correctly.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@mheon  
This is to fix the issue that @mrunalp  saw when we closed the store on an error that may or may not have happened.

**Comment by mheon** [comment]
LGTM

**Comment by mheon** [comment]
bot, retest this please

**Comment by TomSweeneyRedHat** [comment]
LGTM
But interesting golang behavior.

**Pull request closed without merging**
