### PR TITLE
Short options

### PR DESCRIPTION
**Pull request by baude**
Short options!
    
Any subcommand that has two or more booleon short options can
now combine those two options.  For example:
    
kpod rmi -af (Remove all images forceably)

### CODE REVIEW

**Comment by mheon** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
looks like kpod_run.bats line 80 isn't happy.  Output may have changed from BAR?

**Comment by rhatdan** [comment]
LGTM
@rh-atomic-bot r+
Nice work @baude

**Comment by baude** [comment]
merge me

**Pull request closed without merging**
