### PR TITLE
Vendor in latest containers/image

### PR DESCRIPTION
**Pull request by rhatdan**
Some more features.
    docker-archive generates docker legacy compatible images
    Do not create $DiffID subdirectories for layers with no configs
    Ensure the layer IDs in legacy docker/tarfile metadata are unique
    docker-archive: repeated layers are symlinked in the tar file
    sysregistries: remove all trailing slashes
    Improve docker/* error messages
    Fix failure to make auth directory
    Create a new slice in Schema1.UpdateLayerInfos
    Drop unused storageImageDestination.{image,systemContext}
    Load a *storage.Image only once in storageImageSource
    Support gzip for docker-archive files
    Remove .tar extension from blob and config file names
    ostree, src: support copy of compressed layers
    ostree: re-pull layer if it misses uncompressed_digest|uncompressed_size
    image: fix docker schema v1 -> OCI conversion
    Add /etc/containers/certs.d as default certs directory

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
The change LGTM, but there's all kinds of test unhappiness.

**Comment by mheon** [comment]
Looks like an API change in c/image upstream is breaking things

**Comment by mheon** [comment]
@rhatdan Can you rebase to pick up the test flake fix?

**Comment by rhatdan** [comment]
bot, retest this please

**Comment by rhatdan** [comment]
@baude @mheon @TomSweeneyRedHat @umohnani8 PTAL

**Comment by mheon** [comment]
All green, changes LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by mheon** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
