### PR TITLE
Do not lock all containers during pod start

### PR DESCRIPTION
**Pull request by mheon**
This solves a nasty locking issue with getting the path of namespaces for dependencies

Probably a good idea in general to not hold every lock for the full duration of the operation

### CODE REVIEW

**Comment by mheon** [comment]
Only downside of not holding the locks is that containers can be removed out from under us while start is going on. This won't break anything, but you will get nasty error messages saying that a bunch of containers failed to start (the containers that were removed)

**Comment by mheon** [comment]
Added similar changes to stop and kill

**Comment by TomSweeneyRedHat** [comment]
The changes LGTM, I'm concerned about the containers getting removed underneath but I'm not sure if that's worse than hanging for  long periods.  Anything we can add to error messages to clue folks in on why the error might be happening?

**Comment by rhatdan** [comment]
@mheon Could you address @TomSweeneyRedHat concerns so that we can get this merged.

**Comment by mheon** [comment]
I don't think we can get a more specific error on the backend, but ErrNoSuchCtr is probably pretty clear already. When we do `podman pod` commands, we might want to include additional debug output if we see an ErrNoSuchCtr around

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
