### PR TITLE
Add missing podman commands

### PR DESCRIPTION
**Pull request by rhatdan**
podman container cleanup&Refresh
podman pod (Create,rm, ps)

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
LGTM

**Comment by vrothberg** [comment]
LGTM (I assume podman-port is desired as well)

**Comment by vrothberg** [comment]
@rh-atomic-bot r+

**Comment by mheon** [comment]
I think Homu is in bad shape. It's reporting the results of the key=value PR here...

**Comment by rhatdan** [comment]
Merging manually.

**Comment by mheon** [comment]
Or... Wait, did it merge key=value without a DCO?

**Comment by vrothberg** [comment]
> FAIL - does not have a valid DCO

@mheon, do you know what that means?

**Comment by mheon** [comment]
@vrothberg A Signed-off-by line in the commit - `git commit -s`. It seems like Homu merged a commit which didn't have one, and is now complaining on subsequent PRs?

**Comment by vrothberg** [comment]
@mheon, looks like commit ea5fad6c8b35d73f6cc16642bc56f428954aa36e causes it

**Comment by mheon** [comment]
#1105 should fix

**Comment by mheon** [comment]
@rhatdan once #1105 goes in can you rebase and remove the makefile change so we can merge?

**Comment by TomSweeneyRedHat** [comment]
Test issues.  Also should there be some updates to transefer.md too?

**Comment by mheon** [comment]
Transfer.md is a good call, it has a section for commands not in Docker.

Though honestly, we might want to leave cleanup and refresh out of there. I don't see these commands ever being used by users - `cleanup` should be invoked exclusively by Podman itself, `refresh` by packagers (and maaaaybe to try and isolate bugs). Adding more commands might muddy the waters, so to speak.

**Comment by mheon** [comment]
@rh-atomic-bot retry

**Pull request closed without merging**
