### PR TITLE
Add OnBuild support for podman build

### PR DESCRIPTION
**Pull request by rhatdan**
Only supported for docker formated images. OCI Does not support this flag.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@baude This is not working correctly.

```
./bin/podman build --format docker -t onbuild1 -f Dockerfile1 ~dwalsh/buildah/tests/bud/onbuild/
STEP 1: FROM onbuild
STEP 2: RUN touch /onbuild1
ERRO[0000] error cleaning up network if3 for [/bin/sh -c touch /onbuild1]: running [/usr/sbin/iptables -t nat -D POSTROUTING -s 10.88.0.188/16 -j CNI-cd63386d23de001e3642cec9 -m comment --comment name: "podman" id: "buildah-buildah503851799" --wait]: exit status 2: iptables v1.6.2: Couldn't load target `CNI-cd63386d23de001e3642cec9':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.
 
ERRO[0000] error cleaning up network if2 for [/bin/sh -c touch /onbuild1]: running [/usr/sbin/iptables -t nat -D POSTROUTING -s 10.88.0.187/16 -j CNI-cd63386d23de001e3642cec9 -m comment --comment name: "podman" id: "buildah-buildah503851799" --wait]: exit status 2: iptables v1.6.2: Couldn't load target `CNI-cd63386d23de001e3642cec9':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.
 
STEP 3: RUN touch /onbuild2
ERRO[0000] error cleaning up network if3 for [/bin/sh -c touch /onbuild2]: running [/usr/sbin/iptables -t nat -D POSTROUTING -s 10.88.0.191/16 -j CNI-9448ae2ffce3df14c1e40cc8 -m comment --comment name: "podman" id: "buildah-buildah211547968" --wait]: exit status 2: iptables v1.6.2: Couldn't load target `CNI-9448ae2ffce3df14c1e40cc8':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.
 
ERRO[0000] error cleaning up network if2 for [/bin/sh -c touch /onbuild2]: running [/usr/sbin/iptables -t nat -D POSTROUTING -s 10.88.0.190/16 -j CNI-9448ae2ffce3df14c1e40cc8 -m comment --comment name: "podman" id: "buildah-buildah211547968" --wait]: exit status 2: iptables v1.6.2: Couldn't load target `CNI-9448ae2ffce3df14c1e40cc8':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.
 
STEP 4: ONBUILD RUN touch /onbuild3
STEP 5: COMMIT containers-storage:[overlay@/var/lib/containers/storage+/var/run/containers/storage:.override_kernel_check=true]localhost/onbuild1:latest
Getting image source signatures
Skipping fetch of repeat blob sha256:cd7100a72410606589a54b932cabd804a17f9ae5b42a1882bd56d263e02b6215
Skipping fetch of repeat blob sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef
Copying blob sha256:2b6c868d6948eff412c9c25a45808c1a435015824be44d732730257d03c2ad71
 197 B / 197 B [============================================================] 0s
Copying config sha256:ebab681ddb76cbc3c21606b9880659d981daa8d2159dd690c844b7106f2c84ef
 1.66 KB / 1.66 KB [========================================================] 0s
Writing manifest to image destination
Storing signatures
ebab681ddb76cbc3c21606b9880659d981daa8d2159dd690c844b7106f2c84ef
```

**Comment by mheon** [comment]
@rhatdan Are there any docs changes to the podman build manpage we should be picking up from buildah?

**Comment by mheon** [comment]
LGTM

**Comment by mheon** [comment]
@rhatdan Lint errors

**Comment by rhatdan** [comment]
bot, retest this please

**Comment by mheon** [comment]
@rh-atomic-bot r+

**Comment by mheon** [comment]
bot, retest this please

**Comment by mheon** [comment]
@rh-atomic-bot retry

**Comment by rhatdan** [comment]
Rebase and repush, see if it passes the test now.

**Comment by rhatdan** [comment]
bot, retest this please

**Comment by rhatdan** [comment]
Having the Same FAH27 build issue as others. Merging manually.

**Pull request merged**
