### PR TITLE
Touch up tutorial location and install reqs

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>

Changes tutorials.m to a README.md to make it link better.  Adds iptables and atomic-registries to the requirements in install.md.

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
I need to test on Ubuntu, please hold on merging this atm.

**Comment by rhatdan** [comment]
LGTM, waiting your tests.

**Comment by TomSweeneyRedHat** [comment]
OK, I'm done picking and it's working on Ubuntu now.  GTG.

**Comment by mheon** [comment]
LGTM

**Comment by mheon** [comment]
@TomSweeneyRedHat Git validation shows whitespace errors

**Comment by TomSweeneyRedHat** [comment]
Thx @mheon, and ugh. one space after one line.  Just repushed.

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
