### PR TITLE
Add MacAddress to inspect

### PR DESCRIPTION
**Pull request by 42wim**
Use interfaces from cnitypes and use it to find the MacAddress of the container.

### CODE REVIEW

**Comment by mheon** [comment]
You'll also need to clear the new Interfaces field in State at https://github.com/42wim/libpod/blob/467ef9fb6d5bcd82adf3287b47645798d7b7c722/libpod/container_internal.go#L808 and https://github.com/42wim/libpod/blob/467ef9fb6d5bcd82adf3287b47645798d7b7c722/libpod/boltdb_state.go#L182

**Comment by mheon** [comment]
bot, add author to whitelist

**Comment by mheon** [comment]
@42wim Also, your commit is missing a signoff - please add one with `git commit -s --amend` and repush

**Comment by 42wim** [comment]
Ok, nit fixed :)

**Comment by TomSweeneyRedHat** [comment]
LGTM and happy green test buttons.

**Comment by rhatdan** [comment]
Thanks @42wim 
@rh-atomic-bot r+

**Comment by rhatdan** [comment]
@rh-atomic-bot retry

**Comment by mheon** [comment]
Also needs #957 to fix the tests

**Comment by mheon** [comment]
Alright, should be good now
@rh-atomic-bot retry

**Pull request closed without merging**
