### PR TITLE
networking.go tweak iptables functions

### PR DESCRIPTION
**Pull request by baude**
Took duplicated code and merged it into the helper function so only a single
exec was executed.

Signed-off-by: baude <bbaude@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
LGTM

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by mheon** [comment]
Gitvalidation errors on Homu

**Comment by baude** [comment]
@rh-atomic-bot retry

**Comment by mheon** [comment]
@rh-atomic-bot r+

**Comment by baude** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
