### PR TITLE
Refactor container.go

### PR DESCRIPTION
**Pull request by mheon**
Split container.go into 3 separate files to make finding things easier. Also rename containerRuntimeInfo to containerState, because everything refers to it as state already and having a different name was just confusing.

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
@baude @umohnani8 @TomSweeneyRedHat PTAL

**Comment by umohnani8** [comment]
LGTM

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by TomSweeneyRedHat** [comment]
LGTM fwiw.

**Comment by rhatdan** [comment]
Auto merging is screwed up.  Merging manually.

**Pull request merged**
