### PR TITLE
packagers need the varlink generated file

### PR DESCRIPTION
**Pull request by baude**
Signed-off-by: baude <bbaude@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
@baude Should we also remove the varlink generate dependency from the Makefile targets?

**Comment by mheon** [comment]
@baude Can you add the generated file to https://github.com/projectatomic/libpod/blob/master/.tool/lint#L45 to disable linting it?

**Comment by mheon** [comment]
Or in the `find` statement above in the same file that locates files to test.

**Comment by mheon** [comment]
LGTM once tests pass

**Comment by baude** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
