### PR TITLE
Rename varlink socket and interface

### PR DESCRIPTION
**Pull request by baude**
io.projectatomic.podman -> io.containers.podman

Python changes to be deferred to Jhonce

Signed-off-by: baude <bbaude@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
LGTM. But I'd like to have the corresponding Python changes ready to go when we merge, so we minimize the window of breakage.

**Comment by baude** [comment]
@jwhonce i could do the name changes if you like ... but didnt want to upset any code you might be working on right now (i.e. rebase hell)

**Comment by rhatdan** [comment]
We should move libpod to github.com/containers/libpod this week along with this change.
containers.io is owned by Docker, so the name of the interface is probably bad.
podman.io seems like it is still available or libpod.io.

**Comment by baude** [comment]
This now includes the changes for python

**Comment by baude** [comment]
-> io.podman

**Comment by rhatdan** [comment]
I have reserved podman.io (And buildah.io).

**Comment by rhatdan** [comment]
LGTM

**Comment by mheon** [comment]
LGTM
@rh-atomic-bot r+

**Comment by jwhonce** [comment]
LGTM 👍

**Pull request closed without merging**
