### PR TITLE
urfave/cli: fix parsing of short opts

### PR DESCRIPTION
**Pull request by vrothberg**
Vendor an updated version of urfave/cli to fix the parsing of short
options.  Until the fix is merged upstream, vendor the code from
github.com/vrothberg/cli containing both, the latest urfave/cli and
the bug fix.

Fixes: #714
Signed-off-by: Valentin Rothberg <vrothberg@suse.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
@edsantiago @mheon @baude PTAL

**Comment by giuseppe** [comment]
LGTM, is there an open PR upstream that we can link to?

**Comment by vrothberg** [comment]
> LGTM, is there an open PR upstream that we can link to?

Yes, it's here: https://github.com/projectatomic/libpod/pull/1046#issuecomment-402680150

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

Of course @edsantiago will find a way to break this again. :^)

**Comment by vrothberg** [comment]
> Of course @edsantiago will find a way to break this again. :^)

Challenge accepted :laughing:

**Comment by giuseppe** [comment]
I've tried:
```
podman run --uidmap 0:30000:7000 --gidmap 0:30000:7000  -ti --rm alpine echo hello
```
and it seems that podman now enters an endless loop, I've done a quick test reverting the patch and I don't see the issue anymore.  Does it happen for you as well?

**Comment by vrothberg** [comment]
>  Does it happen for you as well?

Yes, you're good ;-)

**Comment by vrothberg** [comment]
I'll have a look at it to (hopefully) prepare a patch.

**Comment by vrothberg** [comment]
The bug is here: https://github.com/vrothberg/cli/blob/fix-short-opts-parsing/command.go#L207

Instead of adding the argument, the to-be-translated string is added.

**Comment by vrothberg** [comment]
@giuseppe Here's the fix: https://github.com/projectatomic/libpod/pull/1066

I think, the challenge is open again :laughing:

**Pull request closed without merging**
