### PR TITLE
Change stop signal default to SIGTERM

### LINKED ISSUE #298: podman stop for a container takes 10s
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug


**Description**

Everytime I run `podman stop ...` the command takes ~10s to run.

**Steps to reproduce the issue:**

1. start the container

```console
# podman run -d alpine sleep 9999             
4ece26a2904da0184122f2540ed9810ddaaebdd4388b492b58c0cafc7c1b54c2                                         
```

2. see the running container

```console
# podman ps
CONTAINER ID   IMAGE    COMMAND      CREATED AT                      STATUS             PORTS   NAMES
4ece26a2904d   alpine   sleep 9999   2018-02-06 16:40:50 +0000 UTC   Up 5 seconds ago           brave_hugle
```

3. stopping the container

```console
# time podman stop brave_hugle                
4ece26a2904da0184122f2540ed9810ddaaebdd4388b492b58c0cafc7c1b54c2                                         

real    0m10.315s                                   
user    0m0.123s                                    
sys     0m0.049s                                    
```

**Describe the results you received:**

The deletion takes time.

**Describe the results you expected:**

Deletion can happen asynchronously (is that acheivable even though it is just a daemon)?


**Output of `podman version`:**

```console
# podman version                              
Version:       0.1
Go Version:    go1.9.2
Git Commit:    "bf00c976dd7509b7d84d1fa5254f1ac26fc494e5"
Built:         Tue Feb  6 14:58:14 2018
OS/Arch:       linux/amd64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**


```console
# cat /etc/os-release 
NAME=Fedora
VERSION="27 (Cloud Edition)"
ID=fedora
VERSION_ID=27
PRETTY_NAME="Fedora 27 (Cloud Edition)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:27"
HOME_URL="https://fedoraproject.org/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=27
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=27
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Cloud Edition"
VARIANT_ID=cloud
```

```console
# runc -v
runc version 1.0.0-rc4+dev
commit: 97b8bfe7fdea74d5e49b657013455a888328f04e
spec: 1.0.0
```


**CPU Profile**

file: 
[podman-stop.zip](https://github.com/projectatomic/libpod/files/1700040/podman-stop.zip)

above was obtained as follows:

```console
# podman --cpu-profile podman-stop stop jolly_lalande 
af7134f26e5bded8b3f08f15f44d9c0053561cb6a0b75b6226c29efa5cc5582c

# go tool pprof podman-stop          
File: podman                                                                                                                                                                                                       
Build ID: 177139ae37cef8148c544bc1ba759ca5b69c382b  
Type: cpu                                                                                                
Time: Feb 6, 2018 at 5:07pm (UTC)                                                                        
Duration: 10.28s, Total samples = 20ms ( 0.19%)     
Entering interactive mode (type "help" for commands, "o" for options)
...
```

### PR DESCRIPTION
**Pull request by mheon**
Fix #298 
Also add a bit more debugging around signals

### CODE REVIEW

**Comment by rhatdan** [comment]
Can you update the man page also with this text.

```
       Stop a container:  Defaults to send SIGTERM, and then SIGKILL after
        grace period.  The default StopSignal can be overriden during container creation, and
this signal will be sent rather then SIGTERM
```

**Comment by mheon** [comment]
@rhatdan updated the manpage for stop

**Comment by rhatdan** [comment]
BTW I think I introduced this bug...

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by mheon** [comment]
Everything is failing. Looks like internal errors.

**Comment by mheon** [comment]
@rh-atomic-bot retry

**Pull request closed without merging**
