### PR TITLE
PAPR test enhancements

### PR DESCRIPTION
**Pull request by baude**
Signed-off-by: baude <bbaude@redhat.com>

### CODE REVIEW

**Comment by baude** [comment]
bot, retest this please

**Comment by rhatdan** [comment]
LGTM

**Comment by baude** [comment]
lets make sure it passes before merging

**Comment by cgwalters** [comment]
> container create failed: /tmp/

So I suspect everyone writing this code never tested on an ostree-managed system.  Today we have `/tmp` → `/sysroot/tmp`.  There's a long history behind this; see https://github.com/projectatomic/rpm-ostree/pull/778 and https://pagure.io/fedora-kickstarts/pull-request/239 

Since this code is changing namespaces it'll lose `/sysroot`.  I haven't looked in detail, but I'd pass data via a more explicit method (or alternatively perhaps manually chase `/tmp` if it's a symlink?)

**Comment by cgwalters** [comment]
@baude I'd like to help with this, but I'm not finding now the log message I found earlier?  It looks like the PR tip has a generic shell syntax error now.

**Comment by baude** [comment]
bot, retest this please

**Comment by baude** [comment]
bot, retest this please

**Comment by rhatdan** [comment]
@baude Rebase.

**Comment by baude** [comment]
@rh-atomic-bot should be good now

**Comment by mheon** [comment]
Nice work on this one @baude 
LGTM

@rh-atomic-bot r+

**Pull request closed without merging**
