### PR TITLE
Generate varlink API documentation automatically

### PR DESCRIPTION
**Pull request by baude**
Using varlink's idl parser, we generate API documentation for the podman
API relying on the .varlink file as the source.

Signed-off-by: baude <bbaude@redhat.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@baude looks like a rebase is needed.

**Comment by baude** [comment]
bot, retest this please

**Comment by mheon** [comment]
This LGTM once tests are green

**Comment by baude** [comment]
bot, retest this please

**Comment by baude** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
