### PR TITLE
Remove specific versions from python deps

### PR DESCRIPTION
**Pull request by baude**
many of the versions are not available on f28

Signed-off-by: baude <bbaude@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Not sure why this is necessary, since it does say >= for these versions?

**Comment by baude** [comment]
There is no python-dateutil >=2.7 in f28 -> https://koji.fedoraproject.org/koji/packageinfo?packageID=3578
There is no setuptools with that version in f28 either.

**Comment by rhatdan** [comment]
But did @jwhonce say that it required the newer version for some functionality?    IT Will the pypodman work correctly without the newer version?

**Comment by jwhonce** [comment]
@rhatdan @baude I need to get a handle on the python dependencies and builds, that is my plan for Monday.  That version number came in through a pip freeze of my environment which at the time was not a pristine f28.  pristine == Where all eggs are installed via rpm vs. pip.  I also want to chase down why we start the CI environment with python34 then upgrade to python35.  That also caused issues with Friday's build.

Once I get a pristine f28 python environment up and running I'll lock down the requirements.txt to those versions and build/test there.  My plan is to still use >= rather than == in the belief most egg releases add functionality and bugs fixes.

**Comment by rhatdan** [comment]
@jwhonce What should we do with this PR?

**Comment by baude** [comment]
Ill close this but mind you that the current spec follows these requirements.  The current version numbers WILL NOT work on Fedora 28.

**Comment by jwhonce** [comment]
@baude Ack dealing with this in https://github.com/projectatomic/libpod/pull/1106

**Pull request closed without merging**
