### PR TITLE
On success start prints UUID or container name that user inputs

### PR DESCRIPTION
**Pull request by haircommander**
Start now matches docker functionality

Fixes: #1017 

Signed-off-by: haircommander <pehunt@redhat.com>

### CODE REVIEW

**Comment by haircommander** [comment]
@rhatdan  PTAL :)

**Comment by mheon** [comment]
LGTM

**Comment by rhatdan** [comment]
Well that was easy enough.
LGTM
@edsantiago FYI
@rh-atomic-bot r+

**Comment by edsantiago** [comment]
Nice. Thanks!

**Pull request closed without merging**
