### PR TITLE
Add signal proxying to podman run and attach

### LINKED ISSUE #372: podman run & attach: missing or nonfunctional --sig-proxy option
`docker attach` provides a --sig-proxy option, defaulting to true. podman does not offer the equivalent.

I'm not sensing an urgent need for this. Filing issue merely for sake of completeness.

### PR DESCRIPTION
**Pull request by mheon**
Also removes sig-proxy from 'podman create', where is does not make sense.

Fixes #372

### CODE REVIEW

**Comment by mheon** [comment]
Could probably use some tests, but it's also the weekend. I'll get to it sometime on monday.

**Comment by mheon** [comment]
Note to self: does handling SIGWINCH here conflict with #448 - investigate further

**Comment by rhatdan** [comment]
Wouldn't you need it in podman start then?  I thought the podman create was just to make sure that the sig-proxy was setup for start?

**Comment by mheon** [comment]
@rhatdan I don't see `--sig-proxy` in the `docker create` manpage. If we want it in start, I would not be opposed to adding the flag there, though, that's easy enough

**Comment by mheon** [comment]
Answering myself from earlier - Go will forward copies of signals independently to separate channels from `signal.Notify()` so it will not interfere with #448

**Comment by rhatdan** [comment]
I guess it would have to go into podman start --sig-proxy, then.  Not sure why you would do run and attach without start?

**Comment by mheon** [comment]
Docker doesn't have it, but there's no technical reason we can't do it for start --attach. I'll add it in.

**Comment by mheon** [comment]
Added sig-proxy to `podman start` (though flipped from default-true to default-false, because it conflicts with starting multiple containers). Also added integration tests, which are hopefully passing.

**Comment by mheon** [comment]
Sig-proxy seems broken on travis. Will investigate tomorrow.

**Comment by mheon** [comment]
Rebased & force-pushed, let's see if Travis passes now

**Comment by mheon** [comment]
This fails in containers. Still trying to identify the reason

**Comment by rhatdan** [comment]
Seems to have passed tests now?

**Comment by rhatdan** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by mheon** [comment]
Guess it could be a flaky test

**Comment by rhatdan** [comment]
All Green Merging.

**Pull request merged**
