### PR TITLE
Remove kubernetes hostport handling

### LINKED ISSUE #186: Remove Kubernetes hostport manager from Libpod
As the CNI plugins now provide independent hostport management, remove the Kubernetes implementation and provide CNI config files that will enable CNI hostport management.

### PR DESCRIPTION
**Pull request by mheon**
Fixes #186 

This is now handled by CNI plugins, so remove the Kubernetes version

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
@baude @umohnani8 @TomSweeneyRedHat PTAL

**Comment by umohnani8** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by mheon** [comment]
The homu failure is actually merge issues - going to rebase to fix

**Comment by mheon** [comment]
This is ready to merge again

**Comment by mheon** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
