### PR TITLE
Fix libseccomp not working in travis

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

Lets see if this fixes travis ci.

### CODE REVIEW

**Comment by mheon** [comment]
Wait, how did this fix it? We run the Travis tests in containers, so why does having libseccomp on the host matter?

**Comment by mheon** [comment]
Wait, how did this fix it? We run the Travis tests in containers, so why does having libseccomp on the host matter?

**Comment by rhatdan** [comment]
@mheon The dests passed on travis.

**Comment by rhatdan** [comment]
bot, retest this please

**Comment by rhatdan** [comment]
@mheon This is failing during the build phase not in the test phase.  Doesn't this happen outside of the container.

**Comment by mheon** [comment]
@rhatdan I think everything on Travis that is not lint and gofmt should be running in a container

**Comment by rhatdan** [comment]
@jlebon @cevich Any idea what the 

```
Fedora fedora/27/cloud Podman — An internal error occurred. 
```
is all about?

**Comment by jlebon** [comment]
@rhatdan CI infra has the hiccups this morning.

**Comment by cevich** [comment]
@rhatdan what jlebon said.  Those status messages come from the underlying tooling, so in this case papr (or it's executor) literally posted that it back to github.

**Pull request closed without merging**
