### PR TITLE
Move libpod under containers/storage

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
LGTM pending tests

**Comment by TomSweeneyRedHat** [comment]
code LGTM, but centos test is unhappy

**Comment by rhatdan** [comment]
@rh-atomic-bot r=TomSweeneyRedHat

**Comment by rhatdan** [comment]
@rh-atomic-bot retry

**Comment by rhatdan** [comment]
@rh-atomic-bot r=TomSweeneyRedHat

**Comment by rhatdan** [comment]
@rh-atomic-bot r=TomSweeneyRedHat

**Comment by mheon** [comment]
LGTM, merging one travis green

**Comment by mheon** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
