### PR TITLE
Log all output of logrus to syslog as well as stdout/stderr

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Fixes https://github.com/projectatomic/libpod/issues/513

**Comment by mheon** [comment]
LGTM. Always good when these things turn out to be simple changes.

**Comment by baude** [comment]
LGTM but issue with the vendoring of hooks/syslog ?

**Comment by rhatdan** [comment]
@rh-atomic-bot r=baude

**Pull request closed without merging**
