### PR TITLE
Make 'kpod create' also create the container in runc

### PR DESCRIPTION
**Pull request by mheon**
Split off from #78 where the first commit was causing problems.

### CODE REVIEW

**Comment by mheon** [comment]
@baude PTAL

This was already reviewed under #78 so I think we can just merged if it passes tests

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by mheon** [comment]
@rh-atomic-bot retry

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by baude** [comment]
@rh-atomic-bot retry

**Pull request merged**
