### PR TITLE
Vendor in latest buildah code

### PR DESCRIPTION
**Pull request by rhatdan**
This will add --layers support.
Also add missing information in man pages on podman build features.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@mheon @baude @umohnani8 @TomSweeneyRedHat PTAL

**Comment by mheon** [comment]
LGTM

**Comment by umohnani8** [comment]
LGTM

**Comment by mheon** [comment]
@rh-atomic-bot r=umohnani8

**Pull request closed without merging**
