### PR TITLE
Latest revendoring deleted the cmd dir in varlink

### PR DESCRIPTION
**Pull request by baude**
Signed-off-by: baude <bbaude@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
Remove the gitignore, makefile, and travis.yml

This is why building from a vendor/ dir is a bad idea - vendor tools will automatically remove any code we do not directly use.

**Comment by rhatdan** [comment]
We have been playing with a hack in skopeo to do something like this, to keep man pages.

```
vendor-image:
	vndr -whitelist '^github.com/containers/image/docs/.*' github.com/containers/image
```

But we also add a test to the Makefile to make sure the user did not vendor in something without using this command.
```
test-docs:
	@test -f vendor/github.com/containers/image/docs/policy.json.md || (echo "\
Missing containers/image docs, need to make * vendor-image * \
" && exit 1)
```

**Comment by rhatdan** [comment]
https://github.com/projectatomic/skopeo/pull/491

**Comment by baude** [comment]
Removed unwanted files

**Comment by baude** [comment]
bot, retest this please

**Comment by rhatdan** [comment]
LGTM

**Pull request closed without merging**
