### PR TITLE
Allow podman to read exit codes of removed containers

### PR DESCRIPTION
**Pull request by mheon**
We can read the exit file created by conmon to get the exit code instead of querying libpod.

Also, do not error on cleanup if the container is already gone, as a completely removed container is definitely cleaned up.

Resolves: #527

### CODE REVIEW

**Comment by baude** [comment]
LGTM,  nice clean, quick PR

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by mheon** [comment]
CRI-O uses the same mechanism, and they don't seem to have problems, so I'm not terribly worried.

**Comment by rhatdan** [comment]
Aren't these on /run, so they get culled at reboot.

**Comment by rhatdan** [comment]
Yup, there are potentially lots of issues with that in /run. But CRI-O is much more likely to cause that then podman would.

**Pull request closed without merging**
