### PR TITLE
Add accessors to all container config and state fields

### PR DESCRIPTION
**Pull request by mheon**
This way we won't have to grab the entire config to look up individual items

Note: does not have accessors for the spec yet

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM, only wish there was a way to automate this or at least test when someone adds a new field, that there is an accessor

**Comment by TomSweeneyRedHat** [comment]
Changes LGTM, smoketested got smoked though.

**Comment by mheon** [comment]
bot, retest this please

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by mheon** [comment]
@rh-atomic-bot retry

**Comment by mheon** [comment]
@rh-atomic-bot r=rhatdan

**Pull request closed without merging**
