### PR TITLE
Update psgo vendor

### PR DESCRIPTION
**Pull request by mheon**
Pick up changes to user handling in psgo

### CODE REVIEW

**Comment by mheon** [comment]
@vrothberg @rhatdan @TomSweeneyRedHat @umohnani8 PTAL

**Comment by vrothberg** [comment]
LGTM. Thanks for picking it up so quickly :)

**Comment by mheon** [comment]
Going to merge manually once travis is green.

**Comment by mheon** [comment]
And there we go.

**Pull request merged**
