### PR TITLE
Bump podman version to match release version

### PR DESCRIPTION
**Pull request by baude**
Signed-off-by: baude <bbaude@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
I think you added a newline to the end of the file. I don't think it should have a newline.

**Comment by baude** [comment]
no newline that i can see

**Comment by mheon** [comment]
@baude I pulled this down to make sure it worked, and the 0.2 seems correctly formatted, but there is a separate issue - `podman version` is still outputting 0.1

**Comment by mheon** [comment]
Nevermind, works after 'make clean'
LGTM

**Comment by baude** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
