### PR TITLE
Only generate the varlink glue code if needed and from the vendor dir

### PR DESCRIPTION
**Pull request by haraldh**

### CODE REVIEW

**Comment by baude** [comment]
thanks @haraldh , when #670 merges, I will test this out.

**Comment by mheon** [comment]
This has the notable advantage of removing two `go get` from builds, which should cut down on network related test flakes

**Comment by mheon** [comment]
bot, add author to whitelist

**Comment by baude** [comment]
this will need #672 first fwiw

**Comment by mheon** [comment]
#672 is why using vendor/ for anything but libraries is a bad idea. The tooling is not made to do this.

**Comment by mheon** [comment]
IMO, we should remove both `go get` from `varlink_generate` and move them to `install.tools`. This will solve the issue locally. CI will still hit it, but we can bump the vendored varlink code when that happens.

**Comment by mheon** [comment]
This is better than what we're doing now. We can optimize the build process further later.
LGTM.

**Comment by baude** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
