### PR TITLE
Do not eat error messages from pullImage

### PR DESCRIPTION
**Pull request by mheon**
Get more detailed error logging out of pullImage so we can report better errors at the command line

### CODE REVIEW

**Comment by mtrmac** [comment]
ACK

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests

**Comment by rhatdan** [comment]
bot, retest this please

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by rhatdan** [comment]
bot, retest this please

**Comment by rhatdan** [comment]
@mheon You might need to repush this.

**Comment by mheon** [comment]
@baude It looks like Varlink broke the build.

**Comment by mheon** [comment]
Failing locally for me as well. Somehow Travis is passing.

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
