### PR TITLE
Block use of /proc/acpi from inside containers

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Note this is currently blocked by SELinux.

**Comment by rhatdan** [comment]
I think we will need to revendor buildah when https://github.com/projectatomic/buildah/pull/853 gets merged, to protect `podman build`

**Comment by vrothberg** [comment]
It doesn't seem to be protected by apparmor (in contrast to other runtimes).

**Comment by mheon** [comment]
Test suite seems to be exploding

**Comment by mheon** [comment]
Reproduced locally - Podman on master can't pull the Alpine image from any configured registry

**Comment by mheon** [comment]
bot, retest this please

**Comment by mheon** [comment]
Code LGTM

**Comment by mheon** [comment]
bot, retest this please

**Comment by mheon** [comment]
This should be good to merge, but I'll wait for travis to finish before we do.

**Comment by mheon** [comment]
Alright, Travis is green, merging
@rh-atomic-bot r+

**Pull request closed without merging**
