### PR TITLE
Cleanup missing whitespace

### PR DESCRIPTION
**Pull request by rhatdan**
Went through the markdown pages which were complaining about whitespace and ran emacs cleanup on them.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
LGTM

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by rhatdan** [comment]
@jlebon @cgwalters Any idea what is hung up here?

**Comment by jlebon** [comment]
@rh-atomic-bot retry

**Pull request closed without merging**
