### PR TITLE
rootless: do not set setgroups to deny when using newuidmap

### PR DESCRIPTION
**Pull request by giuseppe**
It is required only when directly configuring the user namespace.

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
@mheon @umohnani8 @baude @TomSweeneyRedHat PTAL

**Comment by mheon** [comment]
LGTM

**Comment by umohnani8** [comment]
LGTM

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by mheon** [comment]
Wait, what? Did someone manually merge something?

Ah, well...
@rh-atomic-bot retry

**Pull request closed without merging**
