### PR TITLE
[trivial] - fix typo in transfer.md

### PR DESCRIPTION
**Pull request by lberk**
Fix errant ']' in formatting

### CODE REVIEW

**Comment by rhatdan** [comment]
@lberk Please sign your PR
git commit -a --amend -s
git push --force

**Comment by rhatdan** [comment]
LGTM

**Comment by mheon** [comment]
bot, add author to whitelist

**Comment by mheon** [comment]
@rh-atomic-bot retry

**Comment by mheon** [comment]
bot, retest this please

**Comment by mheon** [comment]
@rh-atomic-bot retry

**Comment by mheon** [comment]
@rh-atomic-bot r+

**Comment by mheon** [comment]
@rh-atomic-bot retry

**Comment by rhatdan** [comment]
This is ridiculous I am force merging.  I have no idea what is going on in CI.
@lberk Thanks for the fix.

**Pull request merged**
