### PR TITLE
Makefile: Respect GOBIN

### PR DESCRIPTION
**Pull request by wking**
And use `go env GOBIN` to detect the user's existing preference.

Using [`?=`][1] allows us to skip the `go env` call if we already have `GOBIN` in the environment, or if we don't need `GOBIN` at all (e.g. for the `help` target).  The recursive expansion could cause an issue if the result of the shell expansions included a `$`, but those seem unlikely in `GOBIN`, `GOMD2MAN`, or the manpage paths.

Using `GOMD2MAN` allows us to collapse old `||`-based recipe into a less confusing invocation.  And using a [static pattern rule][2] for `$(MANPAGES)` lets us write a single rule to handle both section 1 and section 5.

[1]: https://www.gnu.org/software/make/manual/html_node/Setting.html
[2]: https://www.gnu.org/software/make/manual/html_node/Static-Usage.html

### CODE REVIEW

**Comment by rhatdan** [comment]
I am fine with this change, as soon as you get the tests to pass.  :^(

**Comment by wking** [comment]
Looks like `$(GOBIN)` is empty (at least in [the Travis tests][1]):

    /bin/sh: 6: /gometalinter: not found

[1]: https://travis-ci.org/projectatomic/libpod/jobs/379345071#L804

**Comment by mheon** [comment]
Tests look to be passing. LGTM.

**Comment by wking** [comment]
On Tue, May 15, 2018 at 04:35:31PM -0700, Matthew Heon wrote:
> Tests look to be passing. LGTM.

My commit message was stale, since I'd shifted some of the ?= around.
I've just pushed 12ab406 -> 44111b7 updating the commit message (and
that's all it does, so I expect it to pass as well ;).

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by mheon** [comment]
Homu is a known flake
@rh-atomic-bot retry

**Comment by rhatdan** [comment]
Sorry @wking Needs rebase, but it was probably caused by another one of your PRs. :^)

**Comment by wking** [comment]
Rebased around #748 with 44111b7 -> e63f3f3.

**Comment by mheon** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
