### PR TITLE
Vendor in latest containers/image and containers/storage

### PR DESCRIPTION
**Pull request by umohnani8**
Made necessary changes to functions to include contex.Context wherever needed

Signed-off-by: umohnani8 <umohnani@redhat.com>

### CODE REVIEW

**Comment by umohnani8** [comment]
@baude @mheon PTAL

**Comment by mheon** [comment]
This makes me very sad, but there's no getting around it if it's in c/storage and c/image. LGTM.

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by mheon** [comment]
@umohnani8 Build failures in the tests

**Comment by baude** [comment]
fix up the issue in the tests and LGTM. Thanks!

**Comment by baude** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
