### PR TITLE
Fix podman build completions

### PR DESCRIPTION
**Pull request by rhatdan**
Fixes: https://github.com/projectatomic/libpod/issues/1076

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@vrothberg @umohnani8 @baude @TomSweeneyRedHat PTAL

**Comment by baude** [comment]
LGTM

**Comment by vrothberg** [comment]
Tested locally.
LGTM

**Comment by giuseppe** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
