### PR TITLE
Clean up network namespaces on container removal

### LINKED ISSUE #163: networking leak nsfs  mounts
when using networking, we are leaking/not cleaning up nsfs mounts after the container stops.

for example, after running:
```
bin/podman --log-level=debug run -it --rm --network=bridge alpine ip a
```
a newly created mount of:
```
nsfs on /run/netns/cni-94a7ea7b-ebad-cff0-56d2-96d6be27db5c type nsfs (rw,seclabel)
```
remains after the container is done executing and removed.

### PR DESCRIPTION
**Pull request by mheon**
Fixes #163

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
@baude @umohnani8 @TomSweeneyRedHat PTAL

**Comment by umohnani8** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
