### PR TITLE
Changes to attach to enable per-stream attaching

### PR DESCRIPTION
**Pull request by mheon**
This allows us to attach to attach to just stdout or stderr or stdin, or any combination of these.

This needs tests, and is having terminal issues, but the code should be complete.

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
Test aren't happy with this mheon.

**Comment by mheon** [comment]
Pushed a fix for terminal attach, which seems to be working fine now. I think I managed to break non-terminal attach, though.

**Comment by mheon** [comment]
Getting closer. Apparently you can't compare interfaces like io.Reader to nil and expect a good result, so I had to restructure things a bit to determine which streams were attaching. Bash in a non-terminal container still not working right, though.

**Comment by mheon** [comment]
Nevermind that "not working right" bit - it works exactly the same as docker, so I think it's good enough. Let me right some tests and we should be golden.

**Comment by mheon** [comment]
Fixes #604

**Comment by mheon** [comment]
Tests added, removing WIP flag

**Comment by mheon** [comment]
bot, retest this please

**Comment by mheon** [comment]
Test failures are unrelated - we're leaking open files somewhere in the tests

**Comment by mheon** [comment]
Ginkgo itself seems to be leaking containers/storage lock FDs

**Comment by mheon** [comment]
#612 should fix tests

**Comment by baude** [comment]
@rh-atomic-bot r+

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Pull request closed without merging**
