### PR TITLE
AppArmor: runtime check if it's enabled on the host

### PR DESCRIPTION
**Pull request by vrothberg**
Check at runtime if AppArmor is enabled on the host.

Signed-off-by: Valentin Rothberg <vrothberg@suse.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
> LGTM assuming happy tests

Finger's crossed. I remember the great battles with Travis around AppArmor :laughing:

**Comment by mheon** [comment]
I like this solution better than just making the tests conditional. LGTM

**Comment by vrothberg** [comment]
`cannot find package "github.com/opencontainers/runc/libcontainer/apparmor"` ... updating

**Comment by vrothberg** [comment]
bot, retest this please

**Comment by vrothberg** [comment]
bot, retest this please

**Comment by vrothberg** [comment]
bot, retest this please

**Comment by vrothberg** [comment]
bot, retest this please

**Comment by vrothberg** [comment]
One last time ... stuck on `Provisioning host...`

**Comment by rhatdan** [comment]
bot, retest this please

**Comment by rhatdan** [comment]
bot, retest this please

**Comment by mheon** [comment]
So travis is green... Going to try and merge
@rh-atomic-bot r+

**Pull request closed without merging**
