### PR TITLE
utils: fix endless write of resize event

### PR DESCRIPTION
**Pull request by giuseppe**
issue introduced with c82166afabd63f6271990be89ffa6609d3dc6712

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
LGTM

**Comment by mheon** [comment]
bot, retest this please

**Comment by TomSweeneyRedHat** [comment]
Change LGTM, but the F28/cloud Podman test is still unhappy.

**Comment by mheon** [comment]
bot, retest this please

**Comment by rhatdan** [comment]
Looks like f28 cloud image is getting the bad libsemanage package.

**Comment by rhatdan** [comment]
Going to force merge since the Fedora 28 problem is not related to this.

**Comment by mheon** [comment]
@rhatdan I think cloud podman is an allowed failure, so we should be able to ignore it and merge with Homu.

Probably should not be an allowed failure (that stems back to the early days of podman-in-podman testing), but it's a good thing for now

**Pull request merged**
