### PR TITLE
language: correct 'vice versa' in docs

### PR DESCRIPTION
**Pull request by edsantiago**
Signed-off-by: Ed Santiago <santiago@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
LGTM

**Comment by edsantiago** [comment]
>Why is this failing

That was my question too. I don't have a sense for libpod CI yet, but was hoping to hear this was a transient system problem.

**Comment by mheon** [comment]
Cloud podman is allowed to fail, that's our podman-in-podman test suite and the tests aren't quite 100% there

**Comment by rhatdan** [comment]
Ok I can force the merge since this is definitely not breaking anything.

**Pull request merged**
