### PR TITLE
Add --all,-a flag to podman images

### PR DESCRIPTION
**Pull request by umohnani8**
podman images will not show intermediate images by default.
To view all images, including intermediate images created during
a build, use the --all flag.

Signed-off-by: umohnani8 <umohnani@redhat.com>

### CODE REVIEW

**Comment by umohnani8** [comment]
@rhatdan @mheon PTAL

**Comment by mheon** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
But unhappy tests....

**Comment by mheon** [comment]
`
  Expected
      <int>: 4
  to be <
      <int>: 4
`

This is a truly spectacular failure. Well done, CI.

**Comment by mheon** [comment]
@umohnani8 On closer inspection, looks like this might be an actual issue, CI is expecting more than 4 images and just getting 4. The message is just so poorly formatted you assume that it can't tell 4 is equal to 4.

**Comment by umohnani8** [comment]
@mheon this is funny. The output should be 3 lines (1 header and 2 images), that is why I was testing for less than 4.
I think I found a better way of checking the lines returned in the output, let's see.

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by TomSweeneyRedHat** [comment]
homu is unhappy, all other tests passed.

**Comment by rhatdan** [comment]
@rh-atomic-bot retry

**Comment by mheon** [comment]
Looks like gitvalidation epoch is messed up. Let me fix that...

**Comment by mheon** [comment]
#957

**Comment by mheon** [comment]
@rh-atomic-bot retry

**Pull request closed without merging**
