### PR TITLE
Added a defer to an Unlock that immediately followed a Lock

### PR DESCRIPTION
**Pull request by haircommander**
Signed-off-by: haircommander <pehunt@redhat.com>

Fixes: #907

### CODE REVIEW

**Comment by mheon** [comment]
I don't have any memory of timing issues here, so I'm inclined to believe
it's just me making silly mistakes. LGTM. Someone not on a cell phone can
trigger the merge :-)

**Comment by umohnani8** [comment]
LGTM. Merging since @mheon gave the go ahead.

**Comment by TomSweeneyRedHat** [comment]
:champagne: toast to @haircommander for the eagle eye.

**Comment by rhatdan** [comment]
@umohnani8 Should not manually merge, use rh-atomic-bot in the future.

**Comment by umohnani8** [comment]
@rhatdan yeah I figured I made a mistake when I did that. Sorry, will use that in future.

**Pull request merged**
