### PR TITLE
Prevent a potential race when stopping containers

### PR DESCRIPTION
**Pull request by mheon**
If sending a signal fails, check if the container is alive. If it is not, it probably stopped on its own before we could send the signal, so don't error out.

Inspired by CRI-O https://github.com/kubernetes-incubator/cri-o/pull/1478

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM, assuming happy tests.

**Comment by mheon** [comment]
@TomSweeneyRedHat Logs is another common flake because of race conditions, I think - the test spins up a container and immediately does a 'logs' on it...

**Comment by mheon** [comment]
bot, retest this please

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
