### PR TITLE
Add support for oom functions

### PR DESCRIPTION
**Pull request by rhatdan**
Add tests for oom-kill-disable and oom-kill-adj

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@mheon @baude @umohnani8 PTAL

**Comment by mheon** [comment]
@rhatdan This looks like just tests and no code? Is it already implemented?

**Comment by rhatdan** [comment]
That might explain why it is not working.

**Comment by rhatdan** [comment]
Might be time for me to leave for the day

**Comment by TomSweeneyRedHat** [comment]
Happy on Travis, but there looks to be some flag difference that's causing centos to spit up.

**Comment by rhatdan** [comment]
@rh-atomic-bot r=TomSweeneyRedHat

**Comment by rhatdan** [comment]
@rh-atomic-bot r=TomSweeneyRedHat

**Pull request closed without merging**
