### PR TITLE
Update .gitignore for Varlink code and gopathok

### PR DESCRIPTION
**Pull request by mheon**
Make sure we don't check generated files into the repo by adding them to the gitignore

### CODE REVIEW

**Comment by baude** [comment]
you shouldnt be updating API.md but rather the .varlink file; else the next make will nuke your changes.

**Comment by baude** [comment]
@mheon would you mind seeing if they are out of sync and if so, then go ahead and commit API.md? I didn't think of that case when making my earlier comment.

**Comment by rhatdan** [comment]
LGTM

**Comment by mheon** [comment]
@baude Sure, I'll check

**Comment by mheon** [comment]
@baude #849

**Comment by mheon** [comment]
@rh-atomic-bot r=rhatdan

**Pull request closed without merging**
