### PR TITLE
docs/tutorials/podman_tutorial.md: Add Ubuntu

### PR DESCRIPTION
**Pull request by baude**
Adding in how to install and run podman on Ubuntu.

Signed-off-by: baude <bbaude@redhat.com>

### CODE REVIEW

**Comment by baude** [comment]
bot, retest this please

**Comment by TomSweeneyRedHat** [comment]
FYI @ipbabble

**Comment by TomSweeneyRedHat** [comment]
Green lights, ship it!

**Comment by baude** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
