### PR TITLE
Podman load can pull in compressed files

### PR DESCRIPTION
**Pull request by umohnani8**
Podman load can now load in docker-archive files that are compressed.

Fixes https://github.com/projectatomic/libpod/issues/404

Signed-off-by: umohnani8 <umohnani@redhat.com>

### CODE REVIEW

**Comment by umohnani8** [comment]
@mheon @rhatdan PTAL

**Comment by mheon** [comment]
LGTM pending tests

**Comment by baude** [comment]
lgtm

**Comment by baude** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
