### PR TITLE
Man page fixes found by https://pagure.io/ManualPageScan

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by baude** [comment]
LGTM

**Comment by mheon** [comment]
LGTM, nice and simple

**Comment by rhatdan** [comment]
@rh-atomic-bot r=mheon

**Comment by rhatdan** [comment]
@rh-atomic-bot r=TomSweeneyRedHat

**Comment by rhatdan** [comment]
Merging Manually.  Since Homu is not responding.

**Pull request merged**
