### PR TITLE
Update containers/storage to pick up overlay driver fix

### PR DESCRIPTION
**Pull request by mheon**
New pinned commit is ff8a6d2bf496daf46ab1a153f783a0f6b8762a54

This includes a fix to error reporting with overlayfs, and will produce more verbose errors when initializing overlayfs fails.

### CODE REVIEW

**Comment by mheon** [comment]
Should fix #545

**Comment by mheon** [comment]
@baude Looks like the c/storage update is breaking the image tests? Maybe a behavior change in how images are removed?

**Comment by mheon** [comment]
Rebased on top of #543 which should fix the issue

**Comment by mheon** [comment]
Tests green, @rhatdan @baude @TomSweeneyRedHat  PTAL

**Comment by baude** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
