### PR TITLE
Wire in ability to retrieve state from runc

### PR DESCRIPTION
**Pull request by mheon**
This wires in the ability to sync container state from runc, which allows us to get things we could not previously - the container's exit code, PID, whether it was OOM killed.

Also exposes container's log file path in the API.

### CODE REVIEW

**Comment by mheon** [comment]
@rhatdan PTAL

**Comment by rhatdan** [comment]
LGTM, needs some tests.

**Comment by rhatdan** [comment]
@baude @umohnani8 PTAL

**Comment by umohnani8** [comment]
LGTM

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
