### PR TITLE
Fedora 27+ include Podman packages

### PR DESCRIPTION
**Pull request by davidstrauss**

### CODE REVIEW

**Comment by mheon** [comment]
Good catch, LGTM

**Comment by mheon** [comment]
@davidstrauss I think you need to sign your commit - `git commit --amend -s` and force-push should be enough.

**Comment by davidstrauss** [comment]
I'll need to get my GPG house in order to sign the commit. I mostly use my GPG hardware tokens for SSH, so I don't have the proper subkey signing stuff configured yet. I've been meaning to fix things, though, so I'll do that and re-push.

**Comment by mheon** [comment]
@davidstrauss Oh, sorry, not a fully GPG signature, just a Signed-off-by line, should have been more clear

**Comment by wking** [comment]
Docs for the missing Signed-off-by are [here][1].

[1]: https://github.com/projectatomic/libpod/blob/v0.5.2/CONTRIBUTING.md#sign-your-prs

**Comment by TomSweeneyRedHat** [comment]
@davidstrauss Thanks for the update and the catch.  We need to get this in sooner rather than later so I've just spun up #779 stealing your update.  Hope you can contribute again in the future!

**Comment by rhatdan** [comment]
Closing for #779 
Thanks @davidstrauss

**Comment by davidstrauss** [comment]
> Thanks for the update and the catch. We need to get this in sooner rather than later so I've just spun up #779 stealing your update. Hope you can contribute again in the future!

No worries. For what it's worth, removing the `Signed-Off-By` requirement would make drive-by contributions (like those from clicking "Edit" on GitHub) easier.

**Pull request closed without merging**
