### PR TITLE
do not allow port related args to be used with --network=container:

### PR DESCRIPTION
**Pull request by rhatdan**
we cannot set additional ports on an existing container namespace, so we should
not allow --network=container with publish or publish-all.

Signed-off-by: baude <bbaude@redhat.com>
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Replaces https://github.com/projectatomic/libpod/pull/850

**Comment by rhatdan** [comment]
@baude @mheon PTAL

**Comment by mheon** [comment]
LGTM

**Comment by baude** [comment]
LGTM

**Comment by rhatdan** [comment]
@rh-atomic-bot r=baude

**Pull request closed without merging**
