### PR TITLE
rootless: do not segfault if the parent already died

### PR DESCRIPTION
**Pull request by giuseppe**
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
@mheon @baude @umohnani8 @TomSweeneyRedHat PTAL

**Comment by mheon** [comment]
LGTM. Good to merge once Travis is green.

**Comment by umohnani8** [comment]
LGTM

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by mheon** [comment]
Homu seems hung
@rh-atomic-bot retry

**Comment by rhatdan** [comment]
Still seems to be hung.  Merging Manually.

**Comment by afbjorklund** [comment]
Opened #1206 for the other part of this problem (#1189)

**Pull request merged**
