### PR TITLE
Add some global options to build

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>

Add some but not all of the Podman global options to the build command.  Need to work out more.  These are the ones that are common with Buildah.  Adds debug logging, root, runroot, storage-driver and storage-opt.

I'll add more in another PR, wanted to get these up as I know folks have been looking for the debug logging.

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@ipbabble fyi

**Comment by ipbabble** [comment]
I like that --debug propagation . LGTM

**Comment by TomSweeneyRedHat** [comment]
bot, retest this please

**Comment by TomSweeneyRedHat** [comment]
bot, retest this please

**Comment by TomSweeneyRedHat** [comment]
@mheon smoketested keeps failing w/o logs/errors.  Known issue?

**Comment by mheon** [comment]
@TomSweeneyRedHat It looks like the Cent VMs on Papr are having issues coming up. Not sure why. Probably related to homu not working at all the last few days.

**Comment by mheon** [comment]
bot, retest this please

**Comment by TomSweeneyRedHat** [comment]
Finally all green for problem child number 2

**Comment by mheon** [comment]
LGTM

**Comment by mheon** [comment]
I'm going to try rh-atomic-bot and see if it's recovered

**Comment by mheon** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
