### PR TITLE
hooks/README: Fix some Markdown typos (e.g. missing runc target)

### PR DESCRIPTION
**Pull request by wking**
I'd accidentally introduced these typos in #772.

### CODE REVIEW

**Comment by rhatdan** [comment]
bot, retest this please

**Comment by wking** [comment]
I'm not sure how Markdown fixes are leading [to][1]:

> ```
> Error determining manifest MIME type for docker://busybox:latest
> ...
> panic: runtime error: invalid memory address or nil pointer dereference [recovered]
> 	panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x1f0 pc=0xa0fb0c]
>
> goroutine 128 [running]:
> testing.tRunner.func1(0xc4205002d0)
> 	/usr/lib/golang/src/testing/testing.go:742 +0x29d
> panic(0xad1180, 0x116f030)
> 	/usr/lib/golang/src/runtime/panic.go:502 +0x229
> github.com/projectatomic/libpod/libpod/image.(*Image).ID(...)
> 	/go/src/github.com/projectatomic/libpod/libpod/image/image.go:257
> github.com/projectatomic/libpod/libpod/image.TestImage_New(0xc4205002d0)
> 	/go/src/github.com/projectatomic/libpod/libpod/image/image_test.go:132 +0x38c
> testing.tRunner(0xc4205002d0, 0xbd0358)
> 	/usr/lib/golang/src/testing/testing.go:777 +0xd0
> created by testing.(*T).Run
> 	/usr/lib/golang/src/testing/testing.go:824 +0x2e0
> FAIL	github.com/projectatomic/libpod/libpod/image	25.636s
> ```

That's seems like a pretty major flake.

[1]: https://s3.amazonaws.com/aos-ci/ghprb/projectatomic/libpod/a8e544c06fa42879be84289d1c50d84e5d9cef69.0.1526775511460090475/output.log

**Comment by rhatdan** [comment]
@baude PTAL, It looks like there is a way to get an Image struct without a valid image field.  If this is ok to happen then those return calls should be checking if i.image has been set and if not return "".

**Comment by mheon** [comment]
Probably a network flake in the image library unit tests. Those tests are not particularly durable, and will segfault fairly consistently if they fail to pull an image down. Should probably look into adding fault tolerance to them at some point.

**Comment by mheon** [comment]
bot, retest this please

**Comment by mheon** [comment]
LGTM once tests are green.

**Comment by mheon** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
