### PR TITLE
TESTING DO NOT MERGE

### PR DESCRIPTION
**Pull request by cevich**

### CODE REVIEW

**Comment by cevich** [comment]
bot, test this damn thing!

**Comment by cevich** [comment]
Yep, sure-nuf it works.  Direct from the horses mouth:

```
19:34:28 [0] INFO: resolving image 'Fedora-Atomic-26'
```

And in the results: https://s3.amazonaws.com/aos-ci/ghprb/projectatomic/libpod/6f7f73cb42ea233c831991e0a34c85bf8c3b530d.0.1510083420155343483/output.log

@nalind @rhatdan ^^^^  My conclusion: selinux is being disabled in the image itself....AND a potential workaround is: use a different image 😀

Here's a command you can use to retrieve all the available images:
https://url.corp.redhat.com/d62ac1e

**Comment by jlebon** [comment]
>  My conclusion: selinux is being disabled in the image itself....AND a potential workaround is: use a different image

Can you expand on this? Did you find that SELinux was disabled in `fedora/26/atomic`? I just checked, and I see it's enabled by default.

> ```
> 19:34:28 [0] INFO: resolving image 'Fedora-Atomic-26'
> ```

Yes, specifying any OpenStack image works, but only because PAPR is lax about actually checking that the `distro` value is one of https://github.com/projectatomic/papr/blob/master/docs/DISTROS.md. But that might change :) (and I'd say *should* be changed -- we don't want to allow any random image to be provisioned). And anyway, once we move away from OSP in favour of direct qemu-kvm, that will break!

Maybe let's debug some more what you were seeing exactly in `fedora/26/atomic`?

**Comment by cevich** [comment]
@jlebon yepyep, and in addition: The <pick a random image> contents may change, obfuscating random and frustrating debugging. I'll mail you privately and cc the others so we can discuss internally...

**Pull request closed without merging**
