### PR TITLE
Change default certs dir to /etc/containers/certs.d

### PR DESCRIPTION
**Pull request by umohnani8**
Updated man pages to reflect the change
Fixes https://github.com/projectatomic/libpod/issues/38 and https://github.com/projectatomic/libpod/issues/39

Signed-off-by: umohnani8 <umohnani@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
@baude @mheon @TomSweeneyRedHat PTAL

**Comment by mheon** [comment]
Are we just changing the c/image vendored files without revendoring? Can we pull in a new version of c/image to get the fix?

**Comment by mheon** [comment]
Nevermind, I'm dumb and didn't see a vendor.conf change
LGTM

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by rhatdan** [comment]
homu seems to be hung merging manually.

**Pull request merged**
