### PR TITLE
Add cap-add and cap-drop to build man page

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>

Add --cap-add and --cap-drop to build man page.  This was recently added in https://github.com/projectatomic/buildah/pull/799.  Also --userns-uid-map/--userns-gid-map had some changes in the Buildah man page, these have been added from https://github.com/projectatomic/buildah/pull/803

### CODE REVIEW

**Comment by mheon** [comment]
LGTM once tests green

**Comment by mheon** [comment]
Varlink generation errors trying to build the tests, looks like?

**Comment by rhatdan** [comment]
Do a 
git checkout vendor/github.com/varlink
Then 
git commit --amend -a -s

**Comment by mheon** [comment]
@rh-atomic-bot r+

**Comment by rhatdan** [comment]
@TomSweeneyRedHat Missing command completions.

**Comment by TomSweeneyRedHat** [comment]
@RHATDAN DOH!

**Comment by rhatdan** [comment]
bot, retest this please

**Comment by TomSweeneyRedHat** [comment]
Another change has been made to the buildah bud man pages, just rewording/reformatting for --userns-uid-map/--userns-gid-map.  I've added those, bumped the Buildah version in vendor.conf again and have my fingers crossed that testing will finally pass.

**Comment by TomSweeneyRedHat** [comment]
bot, retest this please.

**Comment by TomSweeneyRedHat** [comment]
@mheon, bot seems to be ignoring me, could you kick it please?

**Comment by mheon** [comment]
Tests are green, let's give this another go
@rh-atomic-bot r+

**Pull request closed without merging**
