### PR TITLE
Update the version of conmon used in test

### PR DESCRIPTION
**Pull request by rhatdan**
Also start using podmin in /usr/libexec/podman rather then crio.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
LGTM once the test suite comes back up

**Comment by rhatdan** [comment]
@mheon Seems like latest conmon and your sig_proxy tests are not working.  Any ideas?

**Comment by mheon** [comment]
@rhatdan Looks like `podman kill -s 9 $containername` is giving exit code 137 instead of 0. Not sure why

**Comment by mheon** [comment]
Wait, nevermind, I think the `podman kill` is completing successfully, it's the main container that throws an error.

**Comment by mheon** [comment]
@rhatdan That tests looks kind of dodgy - the FIFO bash should be trying to access isn't being created. I think the conmon fixes from @giuseppe around exit codes might have exposed a problem we might not have been seeing before.

**Comment by giuseppe** [comment]
@mheon @rhatdan yes correct.  conmon now returns 128+SIGNAL when the process is signaled, so the 137 exit code is expected in the test that sends a SIGKILL: 128+9

**Comment by mheon** [comment]
Alright. Should be sufficient to set 137 as the expected exit code.

**Comment by mheon** [comment]
Tests are green, LGTM

**Comment by baude** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
