### PR TITLE
Close attach control file

### PR DESCRIPTION
**Pull request by mheon**
Port https://github.com/kubernetes-incubator/cri-o/pull/1288 to libpod

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
@baude @umohnani8 @TomSweeneyRedHat PTAL

**Comment by umohnani8** [comment]
LGTM

**Comment by mheon** [comment]
@rh-atomic-bot r=umohnani8

**Comment by mheon** [comment]
@rh-atomic-bot retry

**Pull request closed without merging**
