### PR TITLE
Add conmon-pidfile flag to bash completions and manpages

### PR DESCRIPTION
**Pull request by mheon**
Missed this when it was first added

### CODE REVIEW

**Comment by rhatdan** [comment]
We should add an example of a systemd unit file using podman to the man page, not for this PR, but something we should definitely document.  I have to make sure sd_notify works and socket activation.

**Comment by rhatdan** [comment]
bot, retest this please

**Comment by mheon** [comment]
@baude @umohnani8 @TomSweeneyRedHat PTAL

**Comment by umohnani8** [comment]
LGTM

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
