### PR TITLE
Makefile: Use a pattern rule for cross-compilation

### PR DESCRIPTION
**Pull request by wking**
Pattern-rule documentation is [here][1].  This commit follows the basic approach from kubernetes-incubator/cri-o#1506, with the portable build tags from kubernetes-incubator/cri-o#1653.

Using `--keep-going` allows folks to see errors for multiple target platforms.  For example, if the Darwin target dies, we'll still attempt to build the Linux target before erroring out.

The Travis test is non-fatal at the moment.  Once it passes, we can remove the `allow_failures` block.

Spun off from [here][2].

[1]: https://www.gnu.org/software/make/manual/html_node/Pattern-Intro.html#Pattern-Intro
[2]: https://github.com/projectatomic/libpod/pull/1015#discussion_r198645420

### CODE REVIEW

**Comment by wking** [comment]
Building for OS X dies, although that's not too surprising.  Interestingly, building for Linux from OS X is dying [with][1]:

```
libpod/container_internal.go:31:2: build constraints exclude all Go files in /Users/travis/gopath/src/github.com/projectatomic/libpod/pkg/rootless
```

I've pushed a461ee66, adjusting the rootless package build tagging.  I don't know if that will address the above error or not, but we'll see :p.

[1]: https://travis-ci.org/projectatomic/libpod/jobs/398461438#L165

**Comment by wking** [comment]
The tip [still has][1] th OS X -> Linux rootless issue.  I don't have time to work up a pure-Go port, and maybe that's not possible or not the issue anyway.  So personally I'm fine with this PR as it stands, and don't expect to be updating it except in response to review comments.

[1]: https://travis-ci.org/projectatomic/libpod/jobs/398692247#L165

**Comment by mheon** [comment]
This LGTM, though we should try waiting until #1047 merges and rebasing on top of that to see if that helps the crosscompile situation any.

**Comment by wking** [comment]
> This LGTM, though we should try waiting until #1047 merges and rebasing on top of that to see if that helps the crosscompile situation any.

Or we could land this so we can easily judge the #1047 improvements ;).  Removing the allowed-failure block once things pass can happen later.

**Comment by wking** [comment]
Rebased around #1048 with a461ee66 -> a086c6a8.

**Comment by wking** [comment]
Rebased around #1047 with a086c6a8 -> de424809, clobbering its `BUILDTAGS_DARWIN` with my [conservative build tags][1].

[1]: https://github.com/projectatomic/libpod/pull/1047#discussion_r200334263

**Comment by mheon** [comment]
@wking I'd prefer to keep the buildtags variable, but I'd be fine replacing its contents with the tags you're using here... I'd generally prefer to keep them separate from the build invocation for ease of reuse/replacement.

**Comment by wking** [comment]
I've pushed caf5374ec -> 46feb2467 to add OS X runs of `gofmt` and `lint`.  I don't know if those tools care about GOOS and other build tags, but #1049 [suggested][1] that at least `gofmt` does.

[1]: https://github.com/projectatomic/libpod/pull/1049#issue-199539638

**Comment by wking** [comment]
> I'd prefer to keep the buildtags variable

I've added a `BUILDTAGS_CROSS` with bcebde9b -> 76e191c9.  I'd have preferred `$(BUILDTAGS_CROSS_$(*))` in the rule, falling back to `$(BUILDTAGS_CROSS)` if the per-target variable was undefined, but couldn't figure out how to do that in GNU Make's syntax.  As it stands, if you want per-target build tags, you'll need to call `make` multiple times:

```console
$ make BUILTAGS_CROSS='what you want for darwin.amd64' bin/podman.cross.darwin.amd64
$ make BUILTAGS_CROSS='what you want for windows.amd64' bin/podman.cross.windows.amd64
```

**Comment by wking** [comment]
`cloud Podman` died [with][1]:

```
>>> CONTAINER_RUNTIME="podman" sh .papr_prepare.sh
+ DIST=Fedora
+ CONTAINER_RUNTIME=podman
+ IMAGE=fedorapodmanbuild
+ PYTHON=python3
+ [[ Fedora != \F\e\d\o\r\a ]]
+ podman build -t fedorapodmanbuild -f Dockerfile.Fedora .
### EXITED WITH CODE 125 AFTER 25s
```

Are there logs anywhere to help figure that out?

[1]: https://s3.amazonaws.com/aos-ci/ghprb/projectatomic/libpod/76e191c91194e81f6b88295383953ef43397f0cd.2.1530814502409856975/output.log

**Comment by mheon** [comment]
bot, retest this please

**Comment by mheon** [comment]
OS X is picking up a bunch of lint errors, plus two build failures due to no buildable files - no buildable files for libseccomp-golang and rootless.

**Comment by mheon** [comment]
Also seems like OS X doesn't have a few C functions we're calling in `cmd/podman/user.go` - it looks like they are in POSIX, but I'm seeing at least anecdotal evidence they aren't available in OS X.

**Comment by wking** [comment]
> ... no buildable files for libseccomp-golang and rootless.

Some notes on the rootless issues [here][1] and [here][2].  I think we can address that and the libseccomp issue in follow-up work, and remove the allowed failure bit once we have.

I'll look at the lint errors now.

[1]: https://github.com/projectatomic/libpod/pull/1034#issuecomment-401571682
[2]: https://github.com/projectatomic/libpod/pull/1034#issuecomment-401868338

**Comment by wking** [comment]
> I'll look at the lint errors now.

I've pushed 76e191c9 -> df68f099 to address the lint errors, which were all "public function became per-platform but the non-Linux version was missing a godoc comment".

**Comment by baude** [comment]
personally i would remove the lint for this PR and do another with it re-enabled.

**Comment by baude** [comment]
the no buildable files is likely something we can attribute to how you are building it; i was not getting that at all.

**Comment by mheon** [comment]
I'm betting the cross build rootless issues are CGo-related - the packages in question both use CGo.

**Comment by wking** [comment]
> personally i would remove the lint for this PR and do another with it re-enabled.

I'm fine either way.  The lint commits are fairly straightforward, although it's taking me a few rounds to get the imports right too (I've just pushed b22541ba -> bf487dc3 as part of that, which is hopefully the last missing piece).

**Comment by wking** [comment]
> the no buildable files is likely something we can attribute to how you are building it; i was not getting that at all.

Maybe because of your broken build-tag declaration which I'm fixing [here][1]?

[1]: https://github.com/projectatomic/libpod/pull/1034/files#diff-bcb65bcc818d0bb8463625dab3e21a05L1

**Comment by mheon** [comment]
@wking It was probably using the linux tag anyways, per https://golang.org/pkg/go/build/ - file names ending in the pattern _$GOOS.go will add an implicit build tag for that GOOS, so `_linux.go` files all assume a `// +build linux` even if not present

**Comment by mheon** [comment]
I'm OK with leaving cross-building Linux on OS X optional and allowed to break if we have working cross-builds of OS X on Linux

**Comment by wking** [comment]
I've pushed bf487dc3 -> d7a2731a changing from `CROSS_COMPILE` to `ALLOWED_TO_FAIL` in `.travis.yml`, and requiring builds from Linux for Linux and OS X to succeed, while continuing to allow builds from OS X to both targets to fail (because of the [rootless issue][1] there).

[1]: https://github.com/projectatomic/libpod/pull/1034#issuecomment-401571682

**Comment by mheon** [comment]
This LGTM, but I'll leave final decision on merge to @baude

**Comment by wking** [comment]
All green here :).

**Comment by baude** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
