### PR TITLE
Aliases do not work with IsSet

### PR DESCRIPTION
**Pull request by rhatdan**
Have to specify all names.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Fixes https://github.com/projectatomic/libpod/issues/928

**Comment by baude** [comment]
LGTM.

**Comment by TomSweeneyRedHat** [comment]
LGTM and happy green test buttons

**Comment by rhatdan** [comment]
@rh-atomic-bot r=baude

**Pull request closed without merging**
