### PR TITLE
remove options from create/run that we cannot support

### PR DESCRIPTION
**Pull request by baude**
Signed-off-by: baude <bbaude@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
The changes LGTM.  Do have a question though.  If these are supported by Docker, do we need to document somewhere that we don't support them?

**Comment by rhatdan** [comment]
We should document in the man pages that we can not support them at this time. I thought there was a chance we could get the --ip and --ip6 support in CNI?

**Comment by mheon** [comment]
@rhatdan Given that we're still waiting on the iptables plugin to merge, I wouldn't count on that being any time soon

**Comment by TomSweeneyRedHat** [comment]
LGTM, a shame that we have to do not implemented though.

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
