### PR TITLE
kpod run, needs to shutdown the storage driver when done

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
@rhatdan There's another `defer runtime.Shutdown(false)` on line 54. I think moving it lower, to right after we start the runtime, is a good thing, but you should remove the extra one so we don't have a duplicate

**Comment by rhatdan** [comment]
Sorry I missed that.  I have moved the defer shutdown up in run.go and create.go.  Even with this change we seem to no be fully closing down the storage.  After running a container, I see containers storage still mounted.  But lets get this merged since this code could clearly leak the runtimes.

**Comment by mheon** [comment]
@rhatdan The mount leaking won't be fixed by shutting down c/storage. We can't tell c/storage to shut down all mounts when we exit (that would kill every running container on the system), which is why we're using runtime.Shutdown(false) to not stop and unmount all containers. The real solution to mount leaking, as I see it, is to fork off a process that uses the kpod wait code to wait until the container stopped, and then unmounts it and performs any necessary cleanup work (--rm for example)

**Comment by mheon** [comment]
This code LGTM though.

**Comment by rhatdan** [comment]
@mheon Don't we have two different situations here.  If I run kpod run without `-d`, kpod continues to run, once it exits, then the container is done.  We should easily be able to handle this, and the --rm flag would work.  --rm is not allowed to be used with `-d`, even with the docker cli.  

Am I incorrect in my assumptions?

**Comment by mheon** [comment]
@rhatdan We could indeed handle both separately, but if we're writing the wait process code already, I think we should just use it for both.

If we want to get things working quickly for the attach case, though, we can probably work add a manual unmount before `kpod run` exits - though even then I think containers can (potentially) outlive kpod run if you detach from the container using the detach keys?

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by rhatdan** [comment]
@rh-atomic-bot r=mheon

**Comment by rhatdan** [comment]
I was thinking more about this over the weekend.  Maybe we should not implement the -d at all, just force you to always run kpod.  If you want to detach then you run it in background.

kpod run -ti fedora command &

Is there really a reason to detach from a running container?  Or does this only make sense in a client server model?

**Comment by mheon** [comment]
Do you want to drop the ability to detach from containers without stopping them entirely? That seems like a major loss of utility. The complete loss of the ability to run service containers (outside of using something like tmux). It makes things simpler architecturally on our side, but I think it loses us a lot in terms of usability.

**Pull request closed without merging**
