### PR TITLE
Make `make localunit` work on macOS

### PR DESCRIPTION
**Pull request by mtrmac**
With this,
```console
make binaries localunit BUILDTAGS='btrfs_noversion libdm_no_deferred_remove exclude_graphdriver_btrfs containers_image_ostree_stub varlink'
```
(i.e. what `make` does, except removing the `seccomp` tag) almost works; only the one more commit in https://github.com/mtrmac/libpod/tree/tests-WIP is necessary.

See the individual commit messages for more details.

RFC:
- Is `checkseccomp` used anywhere? I couldn’t find any reference except for the `Makefile`.
- Is there a clean way to do what https://github.com/mtrmac/libpod/tree/tests-WIP tries to? The tests need to be skipped because the default configuration uses `seccomp`, and that is entirely unrelated from the subject of the test. Both brute-force Linux checks and targeted checks against `seccomp` would work, but the tests could continue to be skipped even if the underlying implementation changes entirely and skipping them were no longer useful.

### CODE REVIEW

**Comment by mheon** [comment]
Checkseccomp is not presently used, but we were planning to add a seccomp tag again, so I'd like to keep it for when we do.

**Comment by mheon** [comment]
I'm fine with a GOOS-based `Skip()` on tests that won't work on a certain architecture.

**Comment by mheon** [comment]
Also, it looks like `checkseccomp` is not what I thought it was - I think we still want to keep it, but we should not be building it anywhere but Linux.

**Comment by mheon** [comment]
I'm generally opposed to the BoltDB state test changes based on whether the command requires reading. We should not be passing states that do not support reading a container out of the database, so we're going to end up ripping these changes out once we implement that.

(Also, there's no reason why the entire `getContainerFromDB()` function is Linux-specific - maybe 2 lines of it actually require Linux...)

**Comment by mtrmac** [comment]
> I'm generally opposed to the BoltDB state test changes based on whether the command requires reading. We should not be passing states that do not support reading a container out of the database, so we're going to end up ripping these changes out once we implement that.

Sure, there’s nothing _inherent_ about reading states not working on macOS.  Would just skipping _all_ Bolt tests in `runForAllStates` on non-Linux, for now, work for you? Maybe gated with a platform-specific boolean constant again, to make sure if this is ever implemented, the tests are re-enabled globally.

> (Also, there's no reason why the entire getContainerFromDB() function is Linux-specific - maybe 2 lines of it actually require Linux...)

Yes, IIRC just this:
```go
		netNS, err := joinNetNS(nsPath)
		if err == nil {
			ctr.state.NetNS = netNS
```

`joinNetNS` ultimately calls `github.com/containernetworking/plugins/pkg/ns`, which has no Linux implementation.

The way `containerPlatformState` works, it can’t represent information for non-native platforms, so loading a Linux object on macOS would lose data. Changing that design to preserve everything, if it were desired, would be a larger project than I’m currently ready to take on.

OTOH if the design goal is that every platform can only read/write its own data, I can pretty trivially factor out the platform-specific parts out of `getContainerFromDB` (and yes, all existing unit tests pass when I modify the code to refuse to load anything with `netNSBytes != nil`!).

So, 3 options WRT `BoltState`:
- Disable tests on non-Linux.
- Decide to reject platform-incompatible containers, tests will pass everywhere.
- Decide to eventually support reading/writing platform-incompatible containers without losing data, and defer making that work.

**Comment by mheon** [comment]
@mtrmac Right now, BoltDB is explicitly set to error if the DB is opened on a machine with another GOOS - so I don't think we have to worry about Mac containers ending up on a Linux system, and vice-versa.

**Comment by mtrmac** [comment]
> Right now, BoltDB is explicitly set to error if the DB is opened on a machine with another GOOS - so I don't think we have to worry about Mac containers ending up on a Linux system, and vice-versa.

Ah, I didn’t notice that. Thanks!

**Comment by mtrmac** [comment]
Updated:
- Dropped the “test requires reading” conditions; kept only a few `s/assert/require/` to avoid panics in tests.
- Made `BoltState.getContainerFromDB` work on all platforms by factoring out the NetNS-specific code into a new function.
- Included the last commit from the `tests-WIP` branch in here as well; this skips some CLI tests based on `GOOS`. The value of working unit tests on macOS is worth a little ugly cross-layer knowledge in tests, I hope.

With this, all unit tests (with the command in the PR description) pass.  The only possibly remaining bit would be to teach `Makefile` to skip the `seccomp` tag on non-Linux.

**Comment by mheon** [comment]
LGTM

**Comment by rhatdan** [comment]
@mtrmac Needs a rebase.

**Comment by mheon** [comment]
@mtrmac Can you rebase against master to fix the tests?

**Comment by mtrmac** [comment]
Rebased.

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
