### PR TITLE
vendor latest containers/psgo

### PR DESCRIPTION
**Pull request by vrothberg**
Signed-off-by: Valentin Rothberg <vrothberg@suse.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
@rhatdan PTAL.

Notice, that I didn't change the return value of `(c *Container) GetContainerPidInformation(descriptors []string) ([]string, error)` to `[][]string` but left a TODO in case we want to support filtering in the future. Otherwise, I had to change varlink (and the python client?).

**Comment by mheon** [comment]
LGTM

**Comment by vrothberg** [comment]
bot, retest this please

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
