### PR TITLE
Make libpod build on 32-bit systems

### PR DESCRIPTION
**Pull request by mheon**
Add a version of getFinishedTime that does not blow up on 32-bit systems

### CODE REVIEW

**Comment by mheon** [comment]
@rhatdan @baude @TomSweeneyRedHat @umohnani8 PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by umohnani8** [comment]
LGTM

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
