### PR TITLE
Bump version to v0.2.2 for ongoing development

### PR DESCRIPTION
**Pull request by mheon**

### CODE REVIEW

**Comment by mheon** [comment]
@rh-atomic-bot r+

**Comment by rhatdan** [comment]
Did we cut a podman 0.2.1 version?

**Comment by mheon** [comment]
Just did

**Comment by TomSweeneyRedHat** [comment]
LGTM, but these versions are spinning faster than a slot reel!  ;^)

**Comment by mheon** [comment]
@TomSweeneyRedHat I gotta cook up a script to do the release process... bump version, tag, bump again for -dev

**Pull request closed without merging**
