### PR TITLE
Bump to v0.6.2

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by wking** [comment]
Looks like you're missing [the dev-bump and epoch commits][1].  For example, see #880 and its three commits.

[1]: https://github.com/projectatomic/libpod/blob/v0.6.1/hack/release.sh#L72-L73

**Comment by rhatdan** [comment]
Looks like the script failed for some reason,  Will try again.

**Comment by rhatdan** [comment]
@wking PTAL

**Comment by rhatdan** [comment]
Passes tests. Manually merging.

**Pull request merged**
