### PR TITLE
Add logo to transfer page

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>

Adds the logo to the transfer page.  You can never have too many selkies!

### CODE REVIEW

**Comment by mheon** [comment]
LGTM

**Comment by mheon** [comment]
bot, retest this please

**Comment by TomSweeneyRedHat** [comment]
flakes, sigh and ouch.

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
