### PR TITLE
runtime: add /usr/libexec/podman/conmon to the conmon paths

### PR DESCRIPTION
**Pull request by giuseppe**
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by mheon** [comment]
I think this is already in `libpod.conf` so this LGTM

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by rhatdan** [comment]
@jlebon FAH27 seems to be in a bad state?

**Comment by rhatdan** [comment]
Well if others pass, we will force merge.

**Comment by jlebon** [comment]
You should be able to reproduce this on a freshly provisioned FAH 27 box:

```
# podman build -t fedorapodmanbuild -f Dockerfile.Fedora .
...
STEP 2: RUN dnf -y install btrfs-progs-devel               atomic-registries               bzip2               conmon               device-mapper-devel               findutils               git               glib2-devel               gnupg               golang               golang-github-cpuguy83-go-md2man               gpgme-devel               libassuan-devel               libseccomp-devel               libselinux-devel               skopeo-containers               runc               make               ostree-devel               python               python3-dateutil               which              golang-github-cpuguy83-go-md2man               procps-ng               iptables && dnf clean all
/tmp/buildah045461068/mnt/rootfs is not an absolute path or is a symlink
panic: runtime error: index out of range

goroutine 1 [running, locked to thread]:
github.com/projectatomic/libpod/vendor/github.com/projectatomic/buildah.runUsingRuntime(0x0, 0x0, 0xc42035a438, 0x4, 0x1d281a0, 0x0, 0x0, 0x1d281a0, 0x0, 0x0, ...)
        /builddir/build/BUILD/libpod-1f2e2a25bf0fec4a1e023a35903627e0562c88a6/_build/src/github.com/projectatomic/libpod/vendor/github.com/projectatomic/buildah/run.go:1059 +0x2ff0
github.com/projectatomic/libpod/vendor/github.com/projectatomic/buildah.runUsingRuntimeMain()
        /builddir/build/BUILD/libpod-1f2e2a25bf0fec4a1e023a35903627e0562c88a6/_build/src/github.com/projectatomic/libpod/vendor/github.com/projectatomic/buildah/run.go:924 +0x3ab
github.com/projectatomic/libpod/vendor/github.com/containers/storage/pkg/reexec.Init(0x10557a0)
        /builddir/build/BUILD/libpod-1f2e2a25bf0fec4a1e023a35903627e0562c88a6/_build/src/github.com/projectatomic/libpod/vendor/github.com/containers/storage/pkg/reexec/reexec.go:26 +0x77
main.main()
        /builddir/build/BUILD/libpod-1f2e2a25bf0fec4a1e023a35903627e0562c88a6/_build/src/github.com/projectatomic/libpod/cmd/podman/main.go:27 +0x71
error building at step {Env:[DISTTAG=f28container FGC=f28  PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin] Command:run Args:[dnf -y install btrfs-progs-devel               atomic-registries               bzip2               conmon               device-mapper-devel               findutils               git               glib2-devel               gnupg               golang               golang-github-cpuguy83-go-md2man               gpgme-devel               libassuan-devel               libseccomp-devel               libselinux-devel               skopeo-containers               runc               make               ostree-devel               python               python3-dateutil               which              golang-github-cpuguy83-go-md2man               procps-ng               iptables && dnf clean all] Flags:[] Attrs:map[] Message:RUN dnf -y install btrfs-progs-devel               atomic-registries               bzip2               conmon               device-mapper-devel               findutils               git               glib2-devel               gnupg               golang               golang-github-cpuguy83-go-md2man               gpgme-devel               libassuan-devel               libseccomp-devel               libselinux-devel               skopeo-containers               runc               make               ostree-devel               python               python3-dateutil               which              golang-github-cpuguy83-go-md2man               procps-ng               iptables && dnf clean all Original:RUN dnf -y install btrfs-progs-devel               atomic-registries               bzip2               conmon               device-mapper-devel               findutils               git               glib2-devel               gnupg               golang               golang-github-cpuguy83-go-md2man               gpgme-devel               libassuan-devel               libseccomp-devel               libselinux-devel               skopeo-containers               runc               make               ostree-devel               python               python3-dateutil               which              golang-github-cpuguy83-go-md2man               procps-ng               iptables && dnf clean all}: exit status 2
```

For some reason, the backtrace doesn't output correctly when redirecting both stdout and stderr to a file, which is why it doesn't show up in the test logs here. You can try redirecting stderr only to a file for that command and archiving it:

```diff
diff --git a/.papr.yml b/.papr.yml
index 353475d..dbd5687 100644
--- a/.papr.yml
+++ b/.papr.yml
@@ -16,6 +16,9 @@ timeout: 45m
 tests:
   - CONTAINER_RUNTIME="podman" sh .papr_prepare.sh

+artifacts:
+  - build.log
+
 context: "FAH27"
 ---

diff --git a/.papr_prepare.sh b/.papr_prepare.sh
index 6fa8eb8..24f55c5 100644
--- a/.papr_prepare.sh
+++ b/.papr_prepare.sh
@@ -11,7 +11,7 @@ if [[ ${DIST} != "Fedora" ]]; then
 fi

 # Build the test image
-${CONTAINER_RUNTIME} build -t ${IMAGE} -f Dockerfile.${DIST} .
+${CONTAINER_RUNTIME} build -t ${IMAGE} -f Dockerfile.${DIST} . 2>build.log

 # Run the tests
 ${CONTAINER_RUNTIME} run --rm --privileged --net=host -v $PWD:/go/src/github.com/projectatomic/libpod --workdir /go/src/github.com/projectatomic/libpod -e PYTHON=$PYTHON -e STORAGE_OPTIONS="--storage-driver=vfs" -e CRIO_ROOT="/go/src/github.com/projectatomic/libpod" -e PODMAN_BINARY="/usr/bin/podman" -e CONMON_BINARY="/usr/libexec/crio/conmon" -e DIST=$DIST $IMAGE sh .papr.sh
```

**Comment by mheon** [comment]
@jlebon Thanks!

**Comment by rhatdan** [comment]
Consistent FAH27 failure, not caused by this PR, Manually merging.

**Pull request merged**
