### PR TITLE
Fix checks for configuration keys in the DB

### PR DESCRIPTION
**Pull request by mheon**
This fixes an issue with our DB checks to ensure we don't open a database with an incompatible configuration. @baude found this while working up a test executable using libpod.

Right now, we don't explicitly set a containers/storage config, so many of the config check keys in the DB will populate with the empty string. Currently, this will throw errors if you explicitly use a storage configuration with the containers/storage defaults (which would be the same as the empty string, given c/storage will just use the default in that case). This resolves this issue by checking against the c/storage defaults as well.

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
@baude @umohnani8 PTAL

**Comment by baude** [comment]
LGTM

**Comment by baude** [comment]
@rh-atomic-bot r+

**Comment by umohnani8** [comment]
LGTM

**Pull request closed without merging**
