### PR TITLE
Remove dependency on kubernetes

### PR DESCRIPTION
**Pull request by baude**
podman parse and attach were using a very small portion of the kubernetes code
but using it caused a signficant increase in binary size.

Signed-off-by: baude <bbaude@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
@baude Needs gofmt

**Comment by mheon** [comment]
@baude Lint errors

**Comment by baude** [comment]
bot, retest this please

**Comment by mheon** [comment]
LGTM. I generally don't like copying things from other projects, but vendoring 75000 lines of code for two structs and a single file is a bit much.

**Comment by rhatdan** [comment]
LGTM
@baude did this shrink the size of podman?

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
