### PR TITLE
Remove kpod rename

### PR DESCRIPTION
**Pull request by mheon**
Libpod containers are immutable once created. They cannot be renamed after created. As such remove kpod rename.

### CODE REVIEW

**Comment by mheon** [comment]
@rhatdan PTAL. We can continue to support this, but it would be a lot of work for not much gain. I'd prefer to just yank it out until someone absolutely requires it.

**Comment by TomSweeneyRedHat** [comment]
I'll let @rhatdan make the go/no go decision on this.  If we do this, you might want to yank out the bash completions stuff too.  Otherwsie LGTM.

**Comment by rhatdan** [comment]
I have no problem yanking this, but I agree get rid of all of it.  Remove from bash completions.

**Comment by mheon** [comment]
Bash completions are gone

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by baude** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
